import {useCallback,useMemo,useState} from 'react'
import {rupiah} from '../../utils/currency'

const dayOf=value=>{const date=new Date(value||0);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10)}
const dateTime=value=>{const date=new Date(value||0);return Number.isNaN(date.getTime())?'-':new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(date)}
const statusOf=order=>String(order?.Status||'pending').toLowerCase()

export default function SuperAdminH2HTransactions({monitor={},accounts=[],onRefresh,onInspect,onRefund}){
  const orders=useMemo(()=>Array.isArray(monitor.orders)?monitor.orders:[],[monitor.orders])
  const accountMap=useMemo(()=>new Map(accounts.map(account=>[String(account.id||account.ID||''),account])),[accounts])
  const[member,setMember]=useState(''),[ref,setRef]=useState(''),[target,setTarget]=useState(''),[product,setProduct]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[perPage,setPerPage]=useState(10),[page,setPage]=useState(1),[selected,setSelected]=useState([])
  const memberOf=useCallback(order=>{const account=accountMap.get(String(order.UserID||''));return account?.email||account?.name||order.UserID||'H2H langsung'},[accountMap])
  const members=useMemo(()=>[...new Set(orders.map(order=>{const account=accountMap.get(String(order.UserID||''));return account?.email||account?.name||order.UserID||'H2H langsung'}))].sort(),[orders,accountMap])
  const products=useMemo(()=>[...new Set(orders.map(order=>order.Product).filter(Boolean))].sort(),[orders])
  const filtered=useMemo(()=>orders.filter(order=>{const day=dayOf(order.CreatedAt);return(!member||memberOf(order)===member)&&(!ref||String(order.RefID||'').toLowerCase().includes(ref.toLowerCase()))&&(!target||String(order.Destination||'').includes(target))&&(!product||order.Product===product)&&(!status||statusOf(order)===status)&&(!from||day>=from)&&(!to||day<=to)}),[orders,member,ref,target,product,status,from,to,memberOf])
  const totalPages=Math.max(1,Math.ceil(filtered.length/perPage)),safePage=Math.min(page,totalPages),rows=filtered.slice((safePage-1)*perPage,safePage*perPage)
  const update=setter=>event=>{setter(event.target.value);setPage(1)}
  const reset=()=>{setMember('');setRef('');setTarget('');setProduct('');setStatus('');setFrom('');setTo('');setPage(1);setSelected([])}
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])
  const togglePage=()=>{const ids=rows.map(order=>order.RefID),all=ids.length&&ids.every(id=>selected.includes(id));setSelected(current=>all?current.filter(id=>!ids.includes(id)):[...new Set([...current,...ids])])}
  const refundSelected=async()=>{for(const order of orders.filter(item=>selected.includes(item.RefID)&&statusOf(item)==='failed'&&!item.Refunded))await onRefund(order);setSelected([])}
  const exportCsv=()=>{const data=[['Waktu','Member','Ref ID','Produk','Tujuan','Qty','Status','Biaya','Keterangan'],...filtered.map(order=>[order.CreatedAt,memberOf(order),order.RefID,order.Product,order.Destination,order.Qty||1,statusOf(order),order.Amount||0,order.Message||order.SN||''])];const csv=data.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=`transaksi-h2h-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)}
  return <section className="owner-h2h-workspace">
    <header><span>OPERASIONAL H2H KUOTAKITA</span><h1>Transaksi H2H</h1><p>Riwayat transaksi member yang diproses melalui provider Pulsa24Jam.</p></header>
    <div className="owner-h2h-filters"><select value={member} onChange={update(setMember)}><option value="">Semua member</option>{members.map(value=><option key={value}>{value}</option>)}</select><input value={ref} onChange={update(setRef)} placeholder="Ref ID"/><input value={target} onChange={update(setTarget)} placeholder="Nomor tujuan"/><select value={product} onChange={update(setProduct)}><option value="">Semua produk</option>{products.map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={update(setStatus)}><option value="">Semua status</option><option value="pending">Pending</option><option value="success">Berhasil</option><option value="failed">Gagal</option></select><input type="date" value={from} max={to||undefined} onChange={update(setFrom)}/><input type="date" value={to} min={from||undefined} onChange={update(setTo)}/><button className="apply" onClick={()=>setPage(1)}>Terapkan</button><button onClick={reset}>Reset</button><button onClick={exportCsv}>Export CSV</button></div>
    <div className="owner-h2h-actions"><span>{selected.length} terpilih</span><button disabled={!selected.some(id=>{const order=orders.find(item=>item.RefID===id);return order&&statusOf(order)==='failed'&&!order.Refunded})} onClick={refundSelected}>Refund gagal terpilih</button><button onClick={onRefresh}>Perbarui status</button><label>Per halaman<select value={perPage} onChange={event=>{setPerPage(Number(event.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select></label></div>
    {monitor.error&&<p className="owner-h2h-error">{monitor.error}</p>}
    <div className="owner-h2h-scroll"><div className="owner-h2h-table"><div className="head"><span>No</span><input type="checkbox" checked={Boolean(rows.length&&rows.every(order=>selected.includes(order.RefID)))} onChange={togglePage}/><span>Waktu</span><span>Member</span><span>Ref ID</span><span>Produk</span><span>Tujuan</span><span>Qty</span><span>Status</span><span>Biaya</span><span>Keterangan</span><span>Aksi</span></div>{rows.map((order,index)=><article key={order.RefID}><span>{(safePage-1)*perPage+index+1}</span><input type="checkbox" checked={selected.includes(order.RefID)} onChange={()=>toggle(order.RefID)}/><time>{dateTime(order.CreatedAt)}</time><span>{memberOf(order)}</span><code>{order.RefID}</code><b>{order.Product||'-'}</b><span>{order.Destination||'-'}</span><span>{order.Qty||1}</span><em className={statusOf(order)}>{statusOf(order)==='success'?'Berhasil':statusOf(order)==='failed'?'Gagal':'Pending'}</em><strong>{rupiah(order.Amount||0)}</strong><span>{order.Message||order.SN||'-'}</span><nav><button onClick={()=>onInspect(order)}>Detail</button>{statusOf(order)==='failed'&&!order.Refunded&&<button className="danger" onClick={()=>onRefund(order)}>Refund</button>}</nav></article>)}{!rows.length&&<p>Belum ada transaksi H2H yang sesuai filter.</p>}</div></div>
    <footer><span>Halaman {safePage} / {totalPages}</span><nav><button disabled={safePage===1} onClick={()=>setPage(1)}>«</button><button disabled={safePage===1} onClick={()=>setPage(value=>value-1)}>‹</button><b>{safePage}</b><button disabled={safePage===totalPages} onClick={()=>setPage(value=>value+1)}>›</button><button disabled={safePage===totalPages} onClick={()=>setPage(totalPages)}>»</button></nav></footer>
  </section>
}
