const config=(title,category,input,placeholder,providers)=>({title,category,input,placeholder,providers})
export const serviceConfig={
  pulsa:config('Isi Pulsa','Pulsa','Nomor Handphone','Contoh: 081234567890',['Telkomsel','Indosat','XL','Tri','AXIS']),
  data:config('Paket Data','Paket Data','Nomor Handphone','Contoh: 081234567890',['Telkomsel','Indosat','XL','Tri','AXIS']),
  ewallet:config('Top Up E-Wallet','E-Wallet','Nomor E-Wallet','Masukkan nomor akun e-wallet',['DANA','GoPay','OVO','ShopeePay','LinkAja']),
  pln:config('Token Listrik PLN','Token PLN','Nomor Meter / ID Pelanggan','Masukkan nomor meter PLN',['PLN']),
  game:config('Voucher & Top Up Game','Voucher Game','User ID Game','Masukkan User ID',['Mobile Legends','Free Fire','PUBG Mobile','Valorant','Genshin Impact']),
  pdam:config('Tagihan PDAM','PDAM','Nomor Pelanggan PDAM','Masukkan nomor pelanggan',['PDAM Jakarta','PDAM Bandung','PDAM Surabaya']),
  bpjs:config('BPJS Kesehatan','BPJS','Nomor Peserta BPJS','Masukkan nomor peserta',['BPJS Kesehatan']),
  telkom:config('Telkom & IndiHome','Internet & TV','Nomor Pelanggan','Masukkan nomor pelanggan',['IndiHome','Telkom']),
  tv:config('TV Berlangganan','Internet & TV','Nomor Pelanggan','Masukkan nomor pelanggan TV',['MNC Vision','K-Vision','Transvision']),
  pascabayar:config('HP Pascabayar','Pascabayar','Nomor Handphone','Masukkan nomor pascabayar',['Telkomsel Halo','Indosat Postpaid','XL Prioritas']),
  gas:config('Tagihan Gas PGN','Tagihan Gas','Nomor Pelanggan','Masukkan nomor pelanggan PGN',['PGN']),
  internet:config('Internet & WiFi','Internet & TV','Nomor Pelanggan','Masukkan nomor pelanggan',['MyRepublic','Biznet','CBN','IndiHome']),
  bank:config('Transfer Bank','Transfer Bank','Nomor Rekening','Masukkan nomor rekening',['BCA','BRI','BNI','Mandiri','Bank Syariah Indonesia']),
  voucher:config('Voucher Digital','Voucher Digital','Nomor Handphone / Email','Masukkan data penerima',['Google Play','Apple Gift Card','Spotify','Vidio']),
  school:config('Pembayaran Pendidikan','Pendidikan','Nomor Siswa / Mahasiswa','Masukkan nomor pelajar',['Sekolah','Universitas','Bimbel']),
  insurance:config('Pembayaran Asuransi','Asuransi','Nomor Polis','Masukkan nomor polis',['Prudential','Allianz','Manulife']),
  vehicle:config('Cicilan Kendaraan','Cicilan','Nomor Kontrak','Masukkan nomor kontrak',['Adira Finance','FIF Group','WOM Finance']),
  property:config('Pajak Bumi & Bangunan','Pajak','Nomor Objek Pajak','Masukkan NOP',['PBB Kota/Kabupaten']),
  travel:config('Tiket Perjalanan','Perjalanan','Nomor Handphone','Masukkan nomor pemesan',['Kereta Api','Pesawat','Bus & Travel']),
  qris:config('Pembayaran QRIS','QRIS','Kode / ID Merchant','Masukkan ID merchant QRIS',['QRIS Nasional','QRIS UMKM','QRIS Dinamis']),
  emoney:config('Top Up Uang Elektronik','Uang Elektronik','Nomor Kartu','Masukkan nomor kartu uang elektronik',['Mandiri e-Money','BCA Flazz','BNI TapCash','BRIZZI']),
  toll:config('Saldo Kartu Tol','Kartu Tol','Nomor Kartu','Masukkan nomor kartu tol',['Mandiri e-Toll','BCA Flazz','BNI TapCash','BRIZZI']),
  streaming:config('Streaming & Musik','Hiburan Digital','Email / Nomor Handphone','Masukkan akun pelanggan',['Netflix','Spotify','YouTube Premium','Disney+ Hotstar','Vidio']),
  esim:config('eSIM & Roaming','Paket eSIM','Nomor Handphone / Email','Masukkan data penerima',['eSIM Indonesia','eSIM Asia','eSIM Global','Paket Roaming']),
  health:config('Klinik & Kesehatan','Kesehatan','Nomor Pasien','Masukkan nomor pasien',['Halodoc','Klinik Digital','Laboratorium','Apotek']),
  creditcard:config('Tagihan Kartu Kredit','Kartu Kredit','Nomor Kartu / Pelanggan','Masukkan nomor kartu',['BCA Card','Mandiri Card','BNI Card','BRI Card','CIMB Niaga']),
  multifinance:config('Cicilan Multifinance','Multifinance','Nomor Kontrak','Masukkan nomor kontrak',['Home Credit','Kredivo','Akulaku','Mega Finance']),
  tax:config('Pajak & Penerimaan Negara','Pajak Negara','Kode Billing','Masukkan kode billing',['DJP Online','Pajak Daerah','Samsat Digital','Penerimaan Negara']),
  zakat:config('Zakat & Donasi','Donasi','Nomor Handphone','Masukkan nomor donatur',['BAZNAS','Dompet Dhuafa','Rumah Zakat','Kitabisa']),
  parking:config('Parkir Digital','Parkir','Nomor Kendaraan','Masukkan nomor kendaraan',['Parkee','CentrePark','Sky Parking','Secure Parking']),
  delivery:config('Kurir & Pengiriman','Pengiriman','Nomor Handphone','Masukkan nomor pengirim',['JNE','J&T Express','SiCepat','Pos Indonesia','AnterAja']),
}
export const allServices=[['Pulsa','pulsa',null,'Komunikasi'],['Paket Data','data',null,'Komunikasi'],['HP Pascabayar','pascabayar',null,'Komunikasi'],['eSIM & Roaming','esim',null,'Komunikasi'],['E-Wallet','ewallet',null,'Keuangan'],['Transfer Bank','bank',null,'Keuangan'],['Pembayaran QRIS','qris',null,'Keuangan'],['Uang Elektronik','emoney',null,'Keuangan'],['Kartu Kredit','creditcard',null,'Keuangan'],['Asuransi','insurance',null,'Keuangan'],['BPJS','bpjs',null,'Tagihan'],['Token PLN','pln',null,'Rumah Tangga'],['PDAM','pdam',null,'Rumah Tangga'],['Gas PGN','gas',null,'Rumah Tangga'],['Internet & WiFi','internet',null,'Rumah Tangga'],['TV Kabel','tv',null,'Hiburan'],['Voucher Game','game',null,'Hiburan'],['Voucher Digital','voucher',null,'Hiburan'],['Streaming & Musik','streaming',null,'Hiburan'],['Klinik & Kesehatan','health',null,'Kesehatan'],['Uang Sekolah','school',null,'Pendidikan'],['Cicilan Kendaraan','vehicle',null,'Cicilan'],['Cicilan Multifinance','multifinance',null,'Cicilan'],['PBB','property',null,'Pajak'],['Pajak & Negara','tax',null,'Pajak'],['Tiket Perjalanan','travel',null,'Perjalanan'],['Saldo Kartu Tol','toll',null,'Perjalanan'],['Parkir Digital','parking',null,'Perjalanan'],['Kurir & Pengiriman','delivery',null,'Perjalanan'],['Zakat & Donasi','zakat',null,'Sosial']]
