import {useEffect,useState} from 'react'
import {Bell,ChevronDown,FileText,HelpCircle,Mail,MessageCircle,ShieldCheck} from 'lucide-react'
import {useLocation} from 'react-router-dom'
import SubPageHeader from '../components/mobile/SubPageHeader'
import MobileNav from '../components/mobile/MobileNav'
import {useAuth} from '../context/AuthContext'
import {appIdentity} from '../config/appIdentity'
import {request} from '../services/http'

export default function AccountFeaturePage(){const{pathname}=useLocation(),{user}=useAuth();if(pathname.endsWith('/notifications'))return <Notifications user={user}/>;if(pathname.endsWith('/help'))return <Help/>;return <Policies/>}
function Notifications({user}){const defaults={transaction:true,promo:true,security:true},[values,setValues]=useState(defaults);useEffect(()=>{request('/me/preferences').then(data=>setValues({...defaults,...(data.notifications||{})})).catch(()=>{})},[user.id]);const toggle=async name=>{const next={...values,[name]:!values[name]};setValues(next);try{const result=await request('/me/preferences',{method:'PUT',body:JSON.stringify({notifications:next})});setValues({...defaults,...(result.notifications||next)})}catch(error){setValues(values)}};return <Shell title="Notifikasi" desc="Atur informasi yang kamu terima"><section className="account-feature-card notification-settings">{[['transaction','Status transaksi','Pembayaran berhasil, gagal, atau diproses'],['promo','Promo KuotaKita','Penawaran dan cashback terbaru'],['security','Keamanan akun','Login dan perubahan pengaturan']].map(([keyValue,title,desc])=><button onClick={()=>toggle(keyValue)} key={keyValue}><i><Bell/></i><div><strong>{title}</strong><small>{desc}</small></div><span className={values[keyValue]?'on':''}><b/></span></button>)}</section></Shell>}
function Help(){const[open,setOpen]=useState(0),faqs=['Bagaimana cara melakukan transaksi?','Kenapa transaksi masih diproses?','Bagaimana menjaga keamanan akun?'];return <Shell title="Pusat Bantuan" desc="FAQ dan layanan pelanggan"><section className="help-contact"><HelpCircle/><h2>Ada yang bisa kami bantu?</h2><p>Temukan jawaban atau hubungi tim dukungan KuotaKita.</p><div><a href={`mailto:${appIdentity.emails.support}?subject=Bantuan%20KuotaKita`}><Mail/>Kirim Email</a><a href={`https://wa.me/${appIdentity.whatsapp}?text=Halo%20KuotaKita%2C%20saya%20membutuhkan%20bantuan.`} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></div><small>Email aplikasi: {appIdentity.emails.app}</small></section><section className="account-feature-card faq-list">{faqs.map((item,index)=><button onClick={()=>setOpen(open===index?-1:index)} key={item}><span><strong>{item}</strong>{open===index&&<small>{index===0?'Pilih layanan, isi data tujuan, pilih produk, lalu konfirmasi pembayaran.':index===1?'Periksa riwayat transaksi. Status akan diperbarui setelah penyedia menyelesaikan proses.':'Jangan berikan PIN atau kata sandi kepada siapa pun, termasuk pihak yang mengaku sebagai KuotaKita.'}</small>}</span><ChevronDown/></button>)}</section></Shell>}
function Policies(){return <Shell title="Syarat & Kebijakan" desc="Ketentuan penggunaan KuotaKita"><section className="policy-hero"><FileText/><div><strong>Transparan dan mudah dipahami</strong><p>Berlaku sejak 21 Juli 2026</p></div></section><section className="account-feature-card policy-copy"><h2>Syarat Penggunaan</h2><p>Pengguna wajib memberikan data yang benar, menjaga keamanan akun, dan memastikan detail transaksi sebelum pembayaran.</p><h2>Privasi</h2><p>KuotaKita menggunakan data akun untuk autentikasi dan pemrosesan layanan. PIN disimpan sebagai hash pada perangkat dan tidak ditampilkan kembali. Pertanyaan privasi dapat dikirim ke {appIdentity.emails.privacy}.</p><h2>Keamanan Pembayaran</h2><p>Verifikasi PIN atau sidik jari bersifat opsional. Pengguna bertanggung jawab menjaga akses perangkat dan akun Google miliknya.</p><div><ShieldCheck/>Data keamanan tidak dibagikan kepada pengguna lain.</div></section></Shell>}
function Shell({title,desc,children}){return <main className="mobile-app account-feature-page"><SubPageHeader title={title} description={desc} back/>{children}<MobileNav/></main>}
