import {useCallback,useEffect,useRef,useState} from 'react'
import {ChevronDown,FileImage,FileText,Loader2,PenLine,Plus,Send,ShieldCheck,Store,Upload,UserRound,X} from 'lucide-react'
import SubPageHeader from '../components/mobile/SubPageHeader'
import MobileNav from '../components/mobile/MobileNav'
import {useAuth} from '../context/AuthContext'
import {request} from '../services/http'
import {rupiah} from '../utils/currency'

const docTypes=[['ktp','KTP pemilik konter','Posisikan seluruh KTP di dalam bingkai'],['store','Foto konter','Pastikan papan nama dan kondisi konter terlihat'],['marketing','Foto bersama marketing','Wajah Agent dan Marketing harus terlihat jelas'],['application','Dokumen pengajuan kredit','Foto seluruh lembar pengajuan dengan jelas']]
const terms=['Data identitas, toko, dan dokumen yang dikirim harus benar serta milik agent.','Operator berhak memeriksa, menyetujui, meminta perbaikan, atau menolak setiap pengajuan.','Modal yang disetujui dicairkan ke Saldo Utama dan wajib dipertanggungjawabkan sesuai perjanjian.','Agent dapat mengajukan kenaikan limit saat pengajuan atau fasilitas sebelumnya masih berjalan; setiap pengajuan tetap diputuskan Operator.']
const captureLocation=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('Perangkat ini tidak mendukung deteksi lokasi. Aktifkan GPS dan gunakan browser terbaru.'));return}navigator.geolocation.getCurrentPosition(position=>{const capturedAt=new Date(),latitude=position.coords.latitude,longitude=position.coords.longitude,accuracy=Math.round(position.coords.accuracy||0),date=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(capturedAt),time=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(capturedAt).replaceAll('.',':');resolve({capturedAt:capturedAt.toISOString(),latitude,longitude,accuracy,date,time,locationLabel:`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`})},error=>reject(new Error(error.code===1?'Izin lokasi wajib diaktifkan agar foto dokumen memiliki cap lokasi.':error.code===3?'Lokasi belum ditemukan. Pastikan GPS aktif lalu coba kembali.':'Lokasi tidak dapat dideteksi. Aktifkan GPS dan coba kembali.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})
const optimizeImage=(file,key,capture)=>new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{try{const ratio=key==='ktp'?85.6/53.98:4/3,maxWidth=key==='ktp'?1280:1120,width=Math.min(maxWidth,image.naturalWidth),height=Math.round(width/ratio),scale=Math.min(width/image.naturalWidth,height/image.naturalHeight),drawWidth=Math.round(image.naturalWidth*scale),drawHeight=Math.round(image.naturalHeight*scale),canvas=document.createElement('canvas'),context=canvas.getContext('2d',{alpha:false}),padding=Math.max(14,Math.round(width*.018)),fontSize=Math.max(16,Math.round(width*.021)),lineHeight=Math.round(fontSize*1.35),overlayHeight=lineHeight*4+padding*2;canvas.width=width;canvas.height=height;context.fillStyle='#f4f8fb';context.fillRect(0,0,width,height);context.drawImage(image,(width-drawWidth)/2,(height-drawHeight)/2,drawWidth,drawHeight);const gradient=context.createLinearGradient(0,height-overlayHeight,0,height);gradient.addColorStop(0,'rgba(3,15,28,.18)');gradient.addColorStop(.3,'rgba(3,15,28,.72)');gradient.addColorStop(1,'rgba(3,15,28,.92)');context.fillStyle=gradient;context.fillRect(0,height-overlayHeight,width,overlayHeight);context.fillStyle='#fff';context.font=`800 ${fontSize}px system-ui, sans-serif`;context.fillText(`ABSEN MASUK  •  ${capture.time} WIB`,padding,height-overlayHeight+padding+fontSize);context.font=`600 ${fontSize}px system-ui, sans-serif`;context.fillText(capture.date,padding,height-overlayHeight+padding+fontSize+lineHeight);context.fillText(`Lokasi GPS: ${capture.locationLabel}`,padding,height-overlayHeight+padding+fontSize+lineHeight*2);context.fillStyle='#bfe8ff';context.fillText(`Akurasi ±${capture.accuracy} meter  •  KuotaKita`,padding,height-overlayHeight+padding+fontSize+lineHeight*3);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.78))}catch(error){URL.revokeObjectURL(url);reject(error)}};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Foto tidak dapat dibaca. Gunakan kamera atau pilih foto JPG/PNG.'))};image.src=url})
const creditStatus=value=>{const raw=String(value||'').trim(),status=raw.toLowerCase();if(status.includes('tolak')||status.includes('gagal')||status.includes('reject')||status.includes('failed'))return{key:'rejected',label:'Ditolak'};if(status.includes('lunas')||status.includes('settled')||status==='paid')return{key:'settled',label:'Lunas'};if(status.includes('setuju')||status.includes('terima')||status.includes('aktif')||status.includes('approve')||status.includes('accept'))return{key:'approved',label:'Diterima'};if(!status||status.includes('menunggu')||status.includes('pending')||status.includes('review')||status.includes('proses'))return{key:'pending',label:'Pending'};return{key:'unknown',label:raw}}
const statusText=status=>creditStatus(status).label
const creditAmount=item=>Number(item?.approvedCapital||item?.approvedAmount||item?.creditOriginalAmount||item?.form?.amount||0)
const isSettled=item=>creditStatus(item?.status).key==='settled'||creditStatus(item?.paymentStatus).key==='settled'
const creditState=item=>isSettled(item)?{key:'settled',label:'Lunas'}:creditStatus(item?.status)
const sortCredits=rows=>[...rows].sort((a,b)=>Number(isSettled(a))-Number(isSettled(b))||creditAmount(b)-creditAmount(a)||new Date(b.createdAt||b.created_at||0)-new Date(a.createdAt||a.created_at||0)||String(a.id||'').localeCompare(String(b.id||'')))

export default function AgentCreditPage(){
 const {user}=useAuth(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[showForm,setShowForm]=useState(false),[docsOpen,setDocsOpen]=useState(false)
 const canvasRef=useRef(null),drawing=useRef(false),syncing=useRef(false)
 const [form,setForm]=useState({amount:'500000',nik:'',homeAddress:'',storeAddress:'',whatsapp:user?.phone||'',email:user?.email||'',storeName:user?.store_name||'',monthlyTransactions:'',familyName:'',familyWhatsapp:'',familyRelation:'',familyAddress:'',purpose:''}),[documents,setDocuments]=useState({}),[accepted,setAccepted]=useState(false),[signed,setSigned]=useState(false)
 const loadApplications=useCallback(async({silent=false}={})=>{if(syncing.current)return;syncing.current=true;try{const result=await request('/me/agent-credit',{noCache:true}),rows=sortCredits(Array.isArray(result)?result:[]);setItems(current=>JSON.stringify(current)===JSON.stringify(rows)?current:rows);if(!silent)setError('')}catch(err){if(!silent)setError(err.message)}finally{syncing.current=false;if(!silent)setLoading(false)}},[])
 useEffect(()=>{const synchronize=()=>{if(document.visibilityState==='visible')loadApplications({silent:true})};loadApplications();const timer=window.setInterval(synchronize,5000);window.addEventListener('focus',synchronize);document.addEventListener('visibilitychange',synchronize);return()=>{window.clearInterval(timer);window.removeEventListener('focus',synchronize);document.removeEventListener('visibilitychange',synchronize)}},[loadApplications])
 const upload=async(event,key)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setError('Dokumen harus berupa foto.');setError('');try{const capture=await captureLocation(),image=await optimizeImage(file,key,capture);setDocuments(value=>({...value,[key]:{name:`${key}-${Date.now()}.jpg`,image,...capture}}))}catch(uploadError){setError(uploadError.message||'Foto belum dapat diproses. Silakan ambil ulang dengan kamera.')}finally{event.target.value=''}}
 const point=event=>{const rect=canvasRef.current.getBoundingClientRect(),source=event.touches?.[0]||event;return{x:(source.clientX-rect.left)*(canvasRef.current.width/rect.width),y:(source.clientY-rect.top)*(canvasRef.current.height/rect.height)}}
 const startDraw=event=>{event.preventDefault();drawing.current=true;event.currentTarget.setPointerCapture?.(event.pointerId);const{x,y}=point(event),context=canvasRef.current.getContext('2d');context.beginPath();context.moveTo(x,y)}
 const moveDraw=event=>{if(!drawing.current)return;event.preventDefault();const{x,y}=point(event),context=canvasRef.current.getContext('2d');context.lineWidth=3;context.lineCap='round';context.strokeStyle='#4f3bd8';context.lineTo(x,y);context.stroke();setSigned(true)}
 const stopDraw=event=>{drawing.current=false;event?.currentTarget?.releasePointerCapture?.(event.pointerId)}
 const clearSignature=()=>{const canvas=canvasRef.current;if(canvas)canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);setSigned(false)}
 const openApplication=items.find(item=>['pending','approved'].includes(creditState(item).key)&&item.partnershipStatus!=='PARTNERSHIP_ENDED')
 const latest=openApplication||items[0],latestForm=latest?.form||{},latestDocs=latest?.documents||{}
 const isLimitIncrease=items.length>0
 const ownerName=latestForm.agentName||user?.name||'Belum dilengkapi',ownerWhatsapp=latestForm.whatsapp||user?.phone||'Belum dilengkapi'
 const activeCredits=items.filter(item=>creditState(item).key==='approved'&&item.partnershipStatus!=='PARTNERSHIP_ENDED')
 const pendingCredits=items.filter(item=>creditState(item).key==='pending'&&item.partnershipStatus!=='PARTNERSHIP_ENDED')
 const creditSummary=activeCredits.reduce((summary,item)=>{const approved=Number(item.approvedCapital||item.approvedAmount||item.creditOriginalAmount||item.form?.amount||0),paid=Number(item.paidAmount||(Array.isArray(item.paymentHistory)?item.paymentHistory.reduce((total,payment)=>total+Number(payment.amount||0),0):0)),remaining=Math.max(0,Number(item.capitalOutstanding??approved));return{total:summary.total+approved,paid:summary.paid+paid,remaining:summary.remaining+remaining}},{total:0,paid:0,remaining:0})
 const documentState=(key)=>{const exists=Boolean(latestDocs[key]||(key==='marketing'&&latestDocs.selfie)||(key==='application'&&latest?.agentConsent?.signature));if(!exists)return'Belum diunggah';return['approved','settled'].includes(creditState(latest).key)?'Disetujui':'Terkirim'}
 const latestState=latest?creditState(latest):null
 const startApplication=()=>{setError('');if(isLimitIncrease)setForm(current=>({...current,...latestForm,amount:'',purpose:''}));setShowForm(true);setTimeout(()=>document.querySelector('.agent-capital-workflow')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}
 const submit=async event=>{event.preventDefault();setError('');setSuccess('');if(!Number(form.amount))return setError('Nominal modal wajib diisi.');if(!form.purpose.trim())return setError('Tujuan penggunaan modal wajib diisi.');if(!isLimitIncrease&&form.nik.length!==16)return setError('NIK harus terdiri dari 16 digit.');if(!isLimitIncrease&&docTypes.some(([key])=>!documents[key]))return setError('Lengkapi seluruh foto dokumen sebelum mengirim.');if(!isLimitIncrease&&!accepted)return setError('Setujui seluruh persyaratan pengajuan terlebih dahulu.');if(!isLimitIncrease&&!signed)return setError('Tanda tangan agent wajib diisi.');setSaving(true);try{const id=`KSA-${Date.now().toString(36).toUpperCase()}`;const payload={id,status:'Menunggu keputusan operator',applicationType:isLimitIncrease?'LIMIT_INCREASE':'INITIAL_CAPITAL',parentApplicationId:isLimitIncrease?latest?.id||'':'',form:{...(isLimitIncrease?latestForm:form),amount:Number(form.amount),purpose:form.purpose,agentName:user?.name||''},...(isLimitIncrease?{}:{documents:Object.fromEntries(Object.entries(documents).map(([key,value])=>[key,{name:value.name,image:value.image,uploadedBy:'agent',capturedAt:value.capturedAt,latitude:value.latitude,longitude:value.longitude,accuracy:value.accuracy,locationLabel:value.locationLabel}])),agentConsent:{name:user?.name,acceptedAt:new Date().toISOString(),signature:canvasRef.current?.toDataURL('image/png')||''}})};const body=JSON.stringify(payload);if(new Blob([body]).size>12*1024*1024)throw new Error('Ukuran seluruh dokumen masih terlalu besar. Ambil ulang foto dengan kamera lalu kirim kembali.');const saved=await request('/me/agent-credit',{method:'POST',body,timeoutMs:45000});setItems(rows=>sortCredits([saved,...rows.filter(item=>item.id!==saved.id)]));setSuccess(isLimitIncrease?'Pengajuan kenaikan limit berhasil dikirim ke Operator.':'Pengajuan berhasil dikirim langsung ke Operator.');setShowForm(false);await loadApplications({silent:true})}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <main className="mobile-app agent-capital-page agent-credit-hub"><SubPageHeader title="Kredit" description="Dukungan modal Agent" back/>
  {loading?<section className="agent-capital-loading"><Loader2/>Memuat data kredit...</section>:<>
   <section className="credit-active-summary"><header><span>MODAL AKTIF</span><strong>{activeCredits.length} fasilitas aktif</strong></header><h2>{rupiah(creditSummary.total)}</h2><div><span><small>Total pembayaran</small><b>{rupiah(creditSummary.paid)}</b></span><span><small>Modal berjalan</small><b>{rupiah(creditSummary.remaining)}</b></span></div></section>
   {!!pendingCredits.length&&<section className="credit-history-card agent-pending-applications"><header><div><span>PENGAJUAN DIPROSES</span><h2>{pendingCredits.length} pengajuan menunggu Operator</h2></div><Loader2/></header><div className="credit-history-list">{pendingCredits.map(item=><article key={`pending-${item.id}`}><header><b>{item.applicationType==='LIMIT_INCREASE'?'Kenaikan/Tambah Kredit':'Pengajuan Kredit'}</b><strong>{rupiah(Number(item.form?.amount)||0)}</strong></header><div><span className="credit-status-text pending">{statusText(item.status)}</span><em className="pending">Sedang diperiksa</em></div><small>{item.id} · Status diperbarui otomatis tanpa refresh.</small></article>)}</div></section>}
   <section className="credit-upload-card"><header><Upload/><h1>Upload Dokumen</h1></header><label>Nama lengkap pemilik toko<input value={ownerName} readOnly/></label><label>Nomor WhatsApp pemilik toko<input value={ownerWhatsapp} readOnly/></label><div className="credit-document-status">{docTypes.map(([key,label])=>{const state=documentState(key);return <div key={key}><span>{label}</span><strong className={state==='Disetujui'?'approved':state==='Terkirim'?'sent':''}>{state}</strong></div>})}</div><button type="button" className="credit-add-button" onClick={startApplication}><Plus/>Ajukan Kenaikan/Tambah Kredit</button>{error&&!showForm&&<p className="agent-capital-error">{error}</p>}</section>
   <section className="credit-files-card"><header><FileText/><h2>Dokumen Pengajuan</h2></header><button type="button" className="credit-files-toggle" onClick={()=>setDocsOpen(value=>!value)}><span><b>Dokumen Saya</b><small>{Object.keys(latestDocs).length+(latest?.agentConsent?.signature?1:0)} dokumen · klik untuk melihat semua</small></span><strong className={latestState?.key||''}>{latestState?.label||'Belum ada'}</strong><ChevronDown className={docsOpen?'open':''}/></button>{docsOpen&&<div className="credit-file-list">{docTypes.map(([key,label])=><div key={key}><span>{label}</span><b>{documentState(key)}</b></div>)}</div>}</section>
   <section className="credit-history-card"><h2>Riwayat Pengajuan</h2>{items.length===0?<p className="credit-empty">Belum ada riwayat pengajuan kredit.</p>:<div className="credit-history-list">{items.map(item=>{const approved=Number(item.approvedCapital||item.approvedAmount||item.form?.amount||0),note=item.operatorDecision?.note||item.reviewNote||item.note||'Belum ada catatan Operator',ended=item.partnershipStatus==='PARTNERSHIP_ENDED',state=creditState(item),active=state.key==='approved'&&!ended,rejectedDocuments=Object.entries(item.documents||{}).filter(([,doc])=>creditStatus(doc?.status).key==='rejected');return <article key={item.id}><header><b>{item.id} · {item.form?.storeName||item.form?.agentName||user?.name}</b><strong>{rupiah(approved)}</strong></header><div><span className={`credit-status-text ${state.key}`}>{state.key==='approved'?'Kredit diterima':state.label}</span><em className={ended?'paid':state.key}>{ended?'Kemitraan berakhir':active?'Modal aktif':state.label}</em></div>{active&&<p>Modal berjalan: {rupiah(Number(item.capitalOutstanding??approved))}</p>}<small><b>{state.key==='rejected'?'Catatan penolakan Operator:':'Catatan Operator:'}</b> {note}</small>{rejectedDocuments.length>0&&<div className="agent-rejected-documents"><b>Dokumen yang ditolak</b>{rejectedDocuments.map(([key,doc])=><p key={key}><strong>{docTypes.find(([type])=>type===key)?.[1]||key}</strong><span>{doc.reviewNote||'Operator belum menambahkan catatan penolakan.'}</span></p>)}</div>}</article>})}</div>}</section>
  </>}
  {showForm&&<form className="agent-credit-form agent-capital-workflow" onSubmit={submit}>
   {isLimitIncrease?<section className="agent-card"><header><i><Plus/></i><div><span>KENAIKAN LIMIT</span><h2>Ajukan Tambahan Kredit</h2><p>Identitas, dokumen, dan persetujuan dari pengajuan pertama digunakan otomatis.</p></div></header><div className="agent-fields"><label>Nama Agent<input value={latestForm.agentName||user?.name||''} readOnly/></label><label>Nama Toko<input value={latestForm.storeName||user?.store_name||''} readOnly/></label><label className="wide">Nominal Tambahan Kredit<input inputMode="numeric" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/\D/g,'')})} required placeholder="Contoh: 500000"/><small>{rupiah(Number(form.amount)||0)} akan ditinjau Operator sebagai kenaikan limit.</small></label><label className="wide">Tujuan Kenaikan Limit<textarea value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} required placeholder="Jelaskan kebutuhan tambahan modal"/></label></div><div className="agent-capital-success"><ShieldCheck/> {Object.keys(latestDocs).length} dokumen lama siap digunakan kembali dari pengajuan {latest?.id}.</div></section>:<>
   <section className="agent-card"><header><i><UserRound/></i><div><span>LANGKAH 1</span><h2>Data Agent & Usaha</h2><p>Isi lengkap sesuai identitas dan kondisi usaha sebenarnya.</p></div></header><div className="agent-fields"><label>Nama Agent<input value={user?.name||''} readOnly/></label><label>Nama Toko<input value={form.storeName} onChange={e=>setForm({...form,storeName:e.target.value})} required placeholder="Nama toko/usaha"/></label><label>NIK<input inputMode="numeric" maxLength="16" value={form.nik} onChange={e=>setForm({...form,nik:e.target.value.replace(/\D/g,'')})} required placeholder="16 digit NIK"/></label><label>Nomor WhatsApp<input inputMode="numeric" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value.replace(/\D/g,'')})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email aktif"/></label><label>Transaksi / Bulan<input inputMode="numeric" value={form.monthlyTransactions} onChange={e=>setForm({...form,monthlyTransactions:e.target.value.replace(/\D/g,'')})} required/></label><label className="wide">Alamat Rumah<textarea value={form.homeAddress} onChange={e=>setForm({...form,homeAddress:e.target.value})} required/></label><label className="wide">Alamat Toko<textarea value={form.storeAddress} onChange={e=>setForm({...form,storeAddress:e.target.value})} required/></label><label className="wide">Nominal Modal<input inputMode="numeric" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/\D/g,'')})} required/><small>{rupiah(Number(form.amount)||0)} akan masuk ke Saldo Utama jika disetujui.</small></label><label className="wide">Tujuan Penggunaan Modal<textarea value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} required/></label></div></section>
   <section className="agent-card"><header><i><Store/></i><div><h2>Kontak Keluarga</h2><p>Kontak yang dapat dihubungi saat proses pemeriksaan.</p></div></header><div className="agent-fields"><label>Nama Keluarga<input value={form.familyName} onChange={e=>setForm({...form,familyName:e.target.value})} required/></label><label>Nomor WhatsApp<input inputMode="numeric" value={form.familyWhatsapp} onChange={e=>setForm({...form,familyWhatsapp:e.target.value.replace(/\D/g,'')})} required/></label><label>Hubungan<input value={form.familyRelation} onChange={e=>setForm({...form,familyRelation:e.target.value})} required placeholder="Orang tua / saudara"/></label><label className="wide">Alamat Keluarga<textarea value={form.familyAddress} onChange={e=>setForm({...form,familyAddress:e.target.value})} required/></label></div></section>
   <section className="agent-card"><header><i><FileImage/></i><div><span>LANGKAH 2</span><h2>Dokumen Pengajuan</h2><p>Izinkan GPS saat mengambil foto. Jam, tanggal, lokasi, dan akurasi akan tercetak otomatis pada foto.</p></div></header><div className="agent-capital-docs">{docTypes.map(([key,label,hint])=><label className={`${documents[key]?'filled':''} document-${key}`} key={key}>{documents[key]?<div className="document-preview"><img src={documents[key].image} alt={`Pratinjau ${label}`}/>{key==='ktp'&&<span className="ktp-face-guide">Area foto</span>}</div>:<div className="document-frame"><FileImage/><b>{key==='ktp'?'Bingkai KTP':'Ambil Foto'}</b></div>}<span><b>{label}</b><small>{documents[key]?`GPS ${documents[key].locationLabel} · ${documents[key].time} WIB`:hint}</small></span><Upload/><input type="file" accept="image/*" capture={key==='marketing'?'user':'environment'} onChange={event=>upload(event,key)}/></label>)}</div></section>
   <section className="agent-card"><header><i><FileText/></i><div><span>LANGKAH 3</span><h2>Persetujuan Persyaratan</h2><p>Baca seluruh ketentuan sebelum menyetujui.</p></div></header><ol className="agent-terms">{terms.map(term=><li key={term}>{term}</li>)}</ol><label className="agent-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Saya telah membaca, memahami, dan menyetujui seluruh persyaratan pengajuan modal KuotaKita.</span></label></section>
   <section className="agent-card"><header><i><PenLine/></i><div><span>LANGKAH 4</span><h2>Tanda Tangan Agent</h2><p>Tanda tangan langsung pada kotak di bawah sebagai persetujuan resmi.</p></div></header><div className="signature-party active"><strong>AGENT</strong><div className="signature-box"><canvas ref={canvasRef} width="640" height="220" onPointerDown={startDraw} onPointerMove={moveDraw} onPointerUp={stopDraw} onPointerCancel={stopDraw} onPointerLeave={stopDraw}/>{!signed&&<span>Tanda tangan di sini</span>}</div><small>{user?.name||'Nama Agent'}</small></div><button type="button" className="clear-signature" onClick={clearSignature}><X/>Hapus tanda tangan</button></section>
   </>}
   {error&&<p className="agent-capital-error">{error}</p>}{success&&<p className="agent-capital-success">{success}</p>}<button className="agent-capital-submit" disabled={saving}><Send/>{saving?'Mengirim...':isLimitIncrease?'Kirim Pengajuan Kenaikan Limit':'Kirim Pengajuan Kemitraan'}</button>
	  </form>}
  <section className="agent-capital-security"><ShieldCheck/><span><b>Pemisahan wewenang aktif</b><small>Marketing hanya mendampingi pendaftaran. Seluruh pemeriksaan dan keputusan modal dilakukan Operator.</small></span></section><MobileNav/>
 </main>
}
