import {useEffect,useRef,useState} from 'react'
import {CheckCircle2,FileImage,FileText,HandCoins,Loader2,PenLine,Send,ShieldCheck,Store,Upload,UserRound,X} from 'lucide-react'
import SubPageHeader from '../components/mobile/SubPageHeader'
import MobileNav from '../components/mobile/MobileNav'
import {useAuth} from '../context/AuthContext'
import {request} from '../services/http'
import {rupiah} from '../utils/currency'

const docTypes=[['ktp','KTP Agent','Posisikan seluruh KTP di dalam bingkai'],['store','Foto Toko','Pastikan papan nama dan kondisi toko terlihat'],['selfie','Selfie Agent memegang KTP','Wajah dan KTP harus terlihat jelas']]
const terms=['Data identitas, toko, dan dokumen yang dikirim harus benar serta milik agent.','Operator berhak memeriksa, menyetujui, meminta perbaikan, atau menolak pengajuan.','Modal yang disetujui dicairkan satu kali ke Saldo Utama dan wajib dipertanggungjawabkan sesuai perjanjian.','Satu agent hanya dapat memiliki satu pengajuan atau modal aktif dalam waktu yang sama.']
const optimizeImage=(file,key)=>new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{try{const ratio=key==='ktp'?85.6/53.98:4/3,maxWidth=key==='ktp'?1600:1440,width=Math.min(maxWidth,image.naturalWidth),height=Math.round(width/ratio),scale=Math.min(width/image.naturalWidth,height/image.naturalHeight),drawWidth=Math.round(image.naturalWidth*scale),drawHeight=Math.round(image.naturalHeight*scale),canvas=document.createElement('canvas'),context=canvas.getContext('2d',{alpha:false});canvas.width=width;canvas.height=height;context.fillStyle='#f4f8fb';context.fillRect(0,0,width,height);context.drawImage(image,(width-drawWidth)/2,(height-drawHeight)/2,drawWidth,drawHeight);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.82))}catch(error){URL.revokeObjectURL(url);reject(error)}};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Foto tidak dapat dibaca. Gunakan kamera atau pilih foto JPG/PNG.'))};image.src=url})
const statusText=status=>status==='Disetujui'?'Modal disetujui':status==='Ditolak'?'Pengajuan ditolak':'Menunggu keputusan Operator'

export default function AgentCreditPage(){
 const {user}=useAuth(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const canvasRef=useRef(null),drawing=useRef(false)
 const [form,setForm]=useState({amount:'500000',nik:'',homeAddress:'',storeAddress:'',whatsapp:user?.phone||'',email:user?.email||'',storeName:user?.store_name||'',monthlyTransactions:'',familyName:'',familyWhatsapp:'',familyRelation:'',familyAddress:'',purpose:''}),[documents,setDocuments]=useState({}),[accepted,setAccepted]=useState(false),[signed,setSigned]=useState(false)
 useEffect(()=>{request('/me/agent-credit',{noCache:true}).then(rows=>setItems(Array.isArray(rows)?rows:[])).catch(err=>setError(err.message)).finally(()=>setLoading(false))},[])
 const upload=async(event,key)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setError('Dokumen harus berupa foto.');setError('');try{const image=await optimizeImage(file,key);setDocuments(value=>({...value,[key]:{name:`${key}-${Date.now()}.jpg`,image}}))}catch(uploadError){setError(uploadError.message||'Foto belum dapat diproses. Silakan ambil ulang dengan kamera.')}finally{event.target.value=''}}
 const point=event=>{const rect=canvasRef.current.getBoundingClientRect(),source=event.touches?.[0]||event;return{x:(source.clientX-rect.left)*(canvasRef.current.width/rect.width),y:(source.clientY-rect.top)*(canvasRef.current.height/rect.height)}}
 const startDraw=event=>{event.preventDefault();drawing.current=true;event.currentTarget.setPointerCapture?.(event.pointerId);const{x,y}=point(event),context=canvasRef.current.getContext('2d');context.beginPath();context.moveTo(x,y)}
 const moveDraw=event=>{if(!drawing.current)return;event.preventDefault();const{x,y}=point(event),context=canvasRef.current.getContext('2d');context.lineWidth=3;context.lineCap='round';context.strokeStyle='#4f3bd8';context.lineTo(x,y);context.stroke();setSigned(true)}
 const stopDraw=event=>{drawing.current=false;event?.currentTarget?.releasePointerCapture?.(event.pointerId)}
 const clearSignature=()=>{const canvas=canvasRef.current;if(canvas)canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);setSigned(false)}
 const openApplication=items.find(item=>item.status!=='Ditolak'&&item.partnershipStatus!=='PARTNERSHIP_ENDED')
 const submit=async event=>{event.preventDefault();setError('');setSuccess('');if(openApplication)return setError('Satu Agent hanya boleh memiliki satu pengajuan/modal aktif.');if(form.nik.length!==16)return setError('NIK harus terdiri dari 16 digit.');if(docTypes.some(([key])=>!documents[key]))return setError('Lengkapi seluruh foto dokumen sebelum mengirim.');if(!accepted)return setError('Setujui seluruh persyaratan pengajuan terlebih dahulu.');if(!signed)return setError('Tanda tangan agent wajib diisi.');setSaving(true);try{const id=`KSA-${Date.now().toString(36).toUpperCase()}`;const payload={id,status:'Menunggu keputusan operator',form:{...form,amount:Number(form.amount),agentName:user?.name||''},documents:Object.fromEntries(Object.entries(documents).map(([key,value])=>[key,{name:value.name,image:value.image,uploadedBy:'agent'}])),agentConsent:{name:user?.name,acceptedAt:new Date().toISOString(),signature:canvasRef.current?.toDataURL('image/png')||''}};const saved=await request('/me/agent-credit',{method:'POST',body:JSON.stringify(payload),timeoutMs:30000});setItems(rows=>[saved,...rows]);setSuccess('Pengajuan berhasil dikirim langsung ke Operator.')}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <main className="mobile-app agent-capital-page"><SubPageHeader title="Program Kemitraan" description="Dukungan pengembangan usaha agent" back/>
  <section className="agent-capital-intro"><i><HandCoins/></i><div><span>DUKUNGAN USAHA AGENT</span><h1>Kembangkan usaha bersama KuotaKita</h1><p>Ajukan dukungan usaha untuk memperkuat transaksi dan pelayanan tokomu. Setiap pengajuan diperiksa secara aman dan transparan oleh Operator.</p></div></section>
  {loading?<section className="agent-capital-loading"><Loader2/>Memuat pengajuan...</section>:openApplication?<section className="agent-capital-status"><header><div><span>PENGAJUAN AKTIF</span><h2>{openApplication.id}</h2></div><strong className={openApplication.status==='Disetujui'?'approved':''}>{statusText(openApplication.status)}</strong></header><dl><div><dt>Nominal diajukan</dt><dd>{rupiah(openApplication.form?.amount||0)}</dd></div><div><dt>Saldo tujuan</dt><dd>Saldo Utama</dd></div><div><dt>Marketing pendaftar</dt><dd>{openApplication.marketingName||'Tercatat otomatis'}</dd></div><div><dt>Keputusan</dt><dd>{statusText(openApplication.status)}</dd></div></dl>{openApplication.status==='Disetujui'&&<p><CheckCircle2/>Dana telah dicairkan satu kali ke Saldo Utama dan kewajiban modal dicatat aman oleh server.</p>}</section>:<form className="agent-credit-form agent-capital-workflow" onSubmit={submit}>
   <section className="agent-card"><header><i><UserRound/></i><div><span>LANGKAH 1</span><h2>Data Agent & Usaha</h2><p>Isi lengkap sesuai identitas dan kondisi usaha sebenarnya.</p></div></header><div className="agent-fields"><label>Nama Agent<input value={user?.name||''} readOnly/></label><label>Nama Toko<input value={form.storeName} onChange={e=>setForm({...form,storeName:e.target.value})} required placeholder="Nama toko/usaha"/></label><label>NIK<input inputMode="numeric" maxLength="16" value={form.nik} onChange={e=>setForm({...form,nik:e.target.value.replace(/\D/g,'')})} required placeholder="16 digit NIK"/></label><label>Nomor WhatsApp<input inputMode="numeric" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value.replace(/\D/g,'')})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email aktif"/></label><label>Transaksi / Bulan<input inputMode="numeric" value={form.monthlyTransactions} onChange={e=>setForm({...form,monthlyTransactions:e.target.value.replace(/\D/g,'')})} required/></label><label className="wide">Alamat Rumah<textarea value={form.homeAddress} onChange={e=>setForm({...form,homeAddress:e.target.value})} required/></label><label className="wide">Alamat Toko<textarea value={form.storeAddress} onChange={e=>setForm({...form,storeAddress:e.target.value})} required/></label><label className="wide">Nominal Modal<input inputMode="numeric" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/\D/g,'')})} required/><small>{rupiah(Number(form.amount)||0)} akan masuk ke Saldo Utama jika disetujui.</small></label><label className="wide">Tujuan Penggunaan Modal<textarea value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} required/></label></div></section>
   <section className="agent-card"><header><i><Store/></i><div><h2>Kontak Keluarga</h2><p>Kontak yang dapat dihubungi saat proses pemeriksaan.</p></div></header><div className="agent-fields"><label>Nama Keluarga<input value={form.familyName} onChange={e=>setForm({...form,familyName:e.target.value})} required/></label><label>Nomor WhatsApp<input inputMode="numeric" value={form.familyWhatsapp} onChange={e=>setForm({...form,familyWhatsapp:e.target.value.replace(/\D/g,'')})} required/></label><label>Hubungan<input value={form.familyRelation} onChange={e=>setForm({...form,familyRelation:e.target.value})} required placeholder="Orang tua / saudara"/></label><label className="wide">Alamat Keluarga<textarea value={form.familyAddress} onChange={e=>setForm({...form,familyAddress:e.target.value})} required/></label></div></section>
   <section className="agent-card"><header><i><FileImage/></i><div><span>LANGKAH 2</span><h2>Dokumen Pengajuan</h2><p>Foto kamera akan dirapikan dan diperkecil otomatis sebelum dikirim.</p></div></header><div className="agent-capital-docs">{docTypes.map(([key,label,hint])=><label className={`${documents[key]?'filled':''} document-${key}`} key={key}>{documents[key]?<div className="document-preview"><img src={documents[key].image} alt={`Pratinjau ${label}`}/>{key==='ktp'&&<span className="ktp-face-guide">Area foto</span>}</div>:<div className="document-frame"><FileImage/><b>{key==='ktp'?'Bingkai KTP':'Ambil Foto'}</b></div>}<span><b>{label}</b><small>{documents[key]?'Foto siap dikirim':hint}</small></span><Upload/><input type="file" accept="image/*" capture={key==='selfie'?'user':'environment'} onChange={event=>upload(event,key)}/></label>)}</div></section>
   <section className="agent-card"><header><i><FileText/></i><div><span>LANGKAH 3</span><h2>Persetujuan Persyaratan</h2><p>Baca seluruh ketentuan sebelum menyetujui.</p></div></header><ol className="agent-terms">{terms.map(term=><li key={term}>{term}</li>)}</ol><label className="agent-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Saya telah membaca, memahami, dan menyetujui seluruh persyaratan pengajuan modal KuotaKita.</span></label></section>
   <section className="agent-card"><header><i><PenLine/></i><div><span>LANGKAH 4</span><h2>Tanda Tangan Agent</h2><p>Tanda tangan langsung pada kotak di bawah sebagai persetujuan resmi.</p></div></header><div className="signature-party active"><strong>AGENT</strong><div className="signature-box"><canvas ref={canvasRef} width="640" height="220" onPointerDown={startDraw} onPointerMove={moveDraw} onPointerUp={stopDraw} onPointerCancel={stopDraw} onPointerLeave={stopDraw}/>{!signed&&<span>Tanda tangan di sini</span>}</div><small>{user?.name||'Nama Agent'}</small></div><button type="button" className="clear-signature" onClick={clearSignature}><X/>Hapus tanda tangan</button></section>
   {error&&<p className="agent-capital-error">{error}</p>}{success&&<p className="agent-capital-success">{success}</p>}<button className="agent-capital-submit" disabled={saving}><Send/>{saving?'Mengirim...':'Kirim Pengajuan Kemitraan'}</button>
  </form>}
  <section className="agent-capital-security"><ShieldCheck/><span><b>Pemisahan wewenang aktif</b><small>Marketing hanya mendampingi pendaftaran. Seluruh pemeriksaan dan keputusan modal dilakukan Operator.</small></span></section><MobileNav/>
 </main>
}
