import {useEffect,useState} from 'react'
import {CheckCircle2,FileImage,HandCoins,Loader2,Send,ShieldCheck,Upload} from 'lucide-react'
import SubPageHeader from '../components/mobile/SubPageHeader'
import MobileNav from '../components/mobile/MobileNav'
import {useAuth} from '../context/AuthContext'
import {request} from '../services/http'
import {rupiah} from '../utils/currency'

const docTypes=[['ktp','KTP Agent'],['store','Foto Toko'],['selfie','Selfie Agent memegang KTP']]
const readImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})
const statusText=status=>status==='Disetujui'?'Modal disetujui':status==='Ditolak'?'Pengajuan ditolak':'Menunggu keputusan Operator'

export default function AgentCreditPage(){
 const {user}=useAuth(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [form,setForm]=useState({amount:'500000',nik:'',storeAddress:'',whatsapp:user?.phone||'',purpose:''}),[documents,setDocuments]=useState({}),[accepted,setAccepted]=useState(false)
 useEffect(()=>{request('/me/agent-credit',{noCache:true}).then(rows=>setItems(Array.isArray(rows)?rows:[])).catch(err=>setError(err.message)).finally(()=>setLoading(false))},[])
 const upload=async(event,key)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setError('Dokumen harus berupa foto.');if(file.size>2500000)return setError('Ukuran foto maksimal 2,5 MB.');const image=await readImage(file);setDocuments(value=>({...value,[key]:{name:file.name,image}}));setError('')}
 const openApplication=items.find(item=>item.status!=='Ditolak'&&item.partnershipStatus!=='PARTNERSHIP_ENDED')
 const submit=async event=>{event.preventDefault();setError('');setSuccess('');if(openApplication)return setError('Satu Agent hanya boleh memiliki satu pengajuan/modal aktif.');if(docTypes.some(([key])=>!documents[key]))return setError('Lengkapi seluruh foto dokumen sebelum mengirim.');if(!accepted)return setError('Setujui pernyataan pengajuan terlebih dahulu.');setSaving(true);try{const id=`KSA-${Date.now().toString(36).toUpperCase()}`;const payload={id,status:'Menunggu keputusan operator',form:{...form,amount:Number(form.amount),agentName:user?.name||'',storeName:user?.store_name||'',email:user?.email||''},documents:Object.fromEntries(Object.entries(documents).map(([key,value])=>[key,{name:value.name,image:value.image,uploadedBy:'agent'}])),agentConsent:{name:user?.name,acceptedAt:new Date().toISOString()}};const saved=await request('/me/agent-credit',{method:'POST',body:JSON.stringify(payload),timeoutMs:30000});setItems(rows=>[saved,...rows]);setSuccess('Pengajuan berhasil dikirim langsung ke Operator.')}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <main className="mobile-app agent-capital-page"><SubPageHeader title="Pengajuan Modal" description="Dikirim langsung ke Operator" back/>
  <section className="agent-capital-intro"><i><HandCoins/></i><div><span>MODAL KEMITRAAN</span><h1>Ajukan modal usaha</h1><p>Modal yang disetujui akan masuk ke Saldo Utama. Tidak ada dompet kredit atau cicilan bulanan terpisah.</p></div></section>
  {loading?<section className="agent-capital-loading"><Loader2/>Memuat pengajuan...</section>:openApplication?<section className="agent-capital-status"><header><div><span>PENGAJUAN AKTIF</span><h2>{openApplication.id}</h2></div><strong className={openApplication.status==='Disetujui'?'approved':''}>{statusText(openApplication.status)}</strong></header><dl><div><dt>Nominal diajukan</dt><dd>{rupiah(openApplication.form?.amount||0)}</dd></div><div><dt>Saldo tujuan</dt><dd>Saldo Utama</dd></div><div><dt>Marketing pendaftar</dt><dd>{openApplication.marketingName||'Tercatat otomatis'}</dd></div><div><dt>Keputusan</dt><dd>{statusText(openApplication.status)}</dd></div></dl>{openApplication.status==='Disetujui'&&<p><CheckCircle2/>Dana telah dicairkan satu kali ke Saldo Utama dan kewajiban modal dicatat aman oleh server.</p>}</section>:<form className="agent-capital-form" onSubmit={submit}><header><span>DATA PENGAJUAN</span><h2>Lengkapi data sendiri</h2><p>Marketing dapat membantu onboarding, tetapi tidak dapat membuka dokumen atau menentukan keputusan modalmu.</p></header><div className="agent-capital-fields"><label><span>Nominal modal</span><input inputMode="numeric" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/\D/g,'')})} required/></label><label><span>NIK</span><input inputMode="numeric" maxLength="16" value={form.nik} onChange={e=>setForm({...form,nik:e.target.value.replace(/\D/g,'')})} required/></label><label><span>Nomor WhatsApp</span><input inputMode="numeric" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value.replace(/\D/g,'')})} required/></label><label><span>Alamat toko</span><textarea value={form.storeAddress} onChange={e=>setForm({...form,storeAddress:e.target.value})} required/></label><label className="wide"><span>Tujuan penggunaan modal</span><textarea value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} required/></label></div><section className="agent-capital-docs"><h3>Dokumen wajib</h3>{docTypes.map(([key,label])=><label className={documents[key]?'filled':''} key={key}><i>{documents[key]?<CheckCircle2/>:<FileImage/>}</i><span><b>{label}</b><small>{documents[key]?.name||'Ambil atau pilih foto yang jelas'}</small></span><Upload/><input type="file" accept="image/*" capture={key==='selfie'?'user':'environment'} onChange={event=>upload(event,key)}/></label>)}</section><label className="agent-capital-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Saya menyatakan data dan foto benar milik saya serta menyetujui pemeriksaan Operator.</span></label>{error&&<p className="agent-capital-error">{error}</p>}{success&&<p className="agent-capital-success">{success}</p>}<button className="agent-capital-submit" disabled={saving}><Send/>{saving?'Mengirim...':'Kirim ke Operator'}</button></form>}
  <section className="agent-capital-security"><ShieldCheck/><span><b>Pemisahan wewenang aktif</b><small>Marketing hanya mendampingi pendaftaran. Seluruh pemeriksaan dan keputusan modal dilakukan Operator.</small></span></section><MobileNav/>
 </main>
}
