import {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {Zap,Eye,EyeOff,UserRound,LockKeyhole,Phone,Mail,ArrowRight,CheckCircle2} from 'lucide-react'
import {useAuth} from '../context/AuthContext'
import {useToast} from '../context/ToastContext'

const loginInitial={username:'',password:''}
const registerInitial={name:'',username:'',phone:'',email:'',password:''}
function Field({form,onChange,name,label,icon:Icon,type='text',placeholder,inputMode}){return <label><span>{label}</span><div><Icon/><input name={name} type={type} value={form[name]||''} onChange={onChange} placeholder={placeholder} inputMode={inputMode} required/></div></label>}

export default function LoginPage(){
 const[mode,setMode]=useState('login'),[form,setForm]=useState(loginInitial),[visible,setVisible]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),{login,register}=useAuth(),{show}=useToast(),navigate=useNavigate()
 const change=e=>setForm({...form,[e.target.name]:e.target.value}),switchMode=next=>{setMode(next);setForm(next==='login'?loginInitial:registerInitial);setError('')}
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{const result=mode==='login'?await login(form):await register(form);navigate(result.user.role==='user'?'/app':'/dashboard')}catch(err){setError(err.message)}finally{setLoading(false)}}
 const props={form,onChange:change}
 return <main className="mobile-auth-page"><section className="auth-phone"><header className="auth-welcome"><div className="auth-logo"><i><Zap/></i><strong>FastPay</strong></div><span>AMAN · CEPAT · PRAKTIS</span><h1>{mode==='login'?'Selamat datang kembali!':'Buat akun FastPay'}</h1><p>{mode==='login'?'Masuk untuk melanjutkan transaksi digitalmu.':'Lengkapi data agar profil dan transaksi akunmu tercatat dengan benar.'}</p></header><section className="auth-sheet"><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>Masuk</button><button className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>Daftar</button></div><form onSubmit={submit}>{mode==='register'&&<><Field {...props} name="name" label="Nama lengkap" icon={UserRound} placeholder="Nama sesuai identitas"/><Field {...props} name="phone" label="Nomor handphone" icon={Phone} placeholder="Contoh: 081234567890" inputMode="numeric"/><Field {...props} name="email" label="Email / Gmail" icon={Mail} type="email" placeholder="nama@gmail.com"/></>}<Field {...props} name="username" label="Nama pengguna" icon={UserRound} placeholder="Masukkan username"/><label><span>Kata sandi</span><div><LockKeyhole/><input name="password" type={visible?'text':'password'} value={form.password} onChange={change} placeholder={mode==='register'?'Minimal 6 karakter':'Masukkan password'} required/><button type="button" onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={loading}>{loading?'Mohon tunggu...':mode==='login'?'Masuk ke FastPay':'Daftar & Buat Akun'}<ArrowRight/></button></form><div className="auth-divider"><span/>atau<span/></div><button className="auth-google" onClick={()=>show('Google Login siap setelah OAuth dikonfigurasi')}><b>G</b><span>Lanjutkan dengan Google</span></button>{mode==='register'&&<div className="register-benefits"><span><CheckCircle2/>Gratis</span><span><CheckCircle2/>Profil lengkap</span><span><CheckCircle2/>Langsung aktif</span></div>}<p className="auth-switch">{mode==='login'?'Belum punya akun?':'Sudah punya akun?'} <button onClick={()=>switchMode(mode==='login'?'register':'login')}>{mode==='login'?'Daftar sekarang':'Masuk di sini'}</button></p><small className="auth-terms">Dengan melanjutkan, kamu menyetujui Syarat Layanan dan Kebijakan Privasi FastPay.</small></section></section></main>
}
