import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {Activity,AlertTriangle,Boxes,CheckCircle2,ClipboardCheck,Eye,Filter,Landmark,Search,ShieldCheck,UserCheck,Users,X} from 'lucide-react'
import {request} from '../services/http'
import {listManagedAgents,updateAgentFollowUp} from '../services/authService'
import {getPulsa24Operations,getPulsa24Products,getTransactions} from '../services/transactionService'
import {rupiah} from '../utils/currency'

const dt=value=>value?new Date(value).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'Belum pernah'
const statusLabel=value=>({ACTIVE:'Aktif',NEED_FOLLOW_UP:'Perlu follow-up',NO_TRANSACTION:'Belum transaksi',PARTNERSHIP_ENDED:'Putus mitra'}[value]||value||'Belum transaksi')
const formOf=item=>item?.form||{}
const documentCount=item=>Object.values(item?.documents||{}).filter(doc=>doc?.image||doc?.dataUrl).length
const hasSignature=item=>Boolean(item?.agentConsent?.signature||item?.agentSignature?.image||item?.signature)
const OPERATOR_VIEW_ALIASES={
 'aktivitas-agent':'transaksi-retail',verifikasi:'pinjaman-retail',peminjam:'pinjaman-retail',agent:'pinjaman-retail','pengajuan-modal':'pinjaman-retail','modal-limit':'pinjaman-retail',
 suspend:'konter-tidak-transaksi',penagihan:'konter-tidak-transaksi','monitoring-agent':'konter-tidak-transaksi',laporan:'overview','kinerja-marketing':'overview',marketing:'overview',
 'transaksi-agent':'transaksi-retail',audit:'overview','follow-up':'konter-tidak-transaksi',pengaturan:'overview',
}
const OPERATOR_VIEWS=new Set(['overview','pinjaman-retail','konter-tidak-transaksi','bank','mapping-provider','transaksi-retail','transaksi-provider','audit-provider'])

export default function OperatorCapitalConsole(){
 const [params]=useSearchParams(),requestedView=params.get('view')||'overview'
 const resolvedView=OPERATOR_VIEW_ALIASES[requestedView]||requestedView
 const view=OPERATOR_VIEWS.has(resolvedView)?resolvedView:'overview'
 const [agents,setAgents]=useState([]),[applications,setApplications]=useState([]),[transactions,setTransactions]=useState([]),[providerOrders,setProviderOrders]=useState([]),[providerProducts,setProviderProducts]=useState([]),[providerLoading,setProviderLoading]=useState(false),[loadedAt]=useState(()=>Date.now()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('SEMUA'),[marketing,setMarketing]=useState('SEMUA'),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[amount,setAmount]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [agentRows,applicationRows,transactionRows]=await Promise.all([listManagedAgents(),request('/agent-credit/applications'),getTransactions().catch(()=>[])]);setAgents(Array.isArray(agentRows)?agentRows:[]);setApplications(Array.isArray(applicationRows)?applicationRows:[]);setTransactions(Array.isArray(transactionRows)?transactionRows:[])}catch(err){setError(err.message||'Data Operator belum dapat dimuat.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(!['bank','mapping-provider','transaksi-provider','audit-provider'].includes(view))return;let active=true;setProviderLoading(true);Promise.all([getPulsa24Operations(),['bank','mapping-provider'].includes(view)?getPulsa24Products():Promise.resolve([])]).then(([operations,products])=>{if(!active)return;setProviderOrders(Array.isArray(operations)?operations:Array.isArray(operations?.orders)?operations.orders:[]);setProviderProducts(Array.isArray(products)?products:Array.isArray(products?.items)?products.items:[])}).catch(err=>{if(active)setMessage(err.message||'Data H2H belum dapat dimuat oleh Operator.')}).finally(()=>{if(active)setProviderLoading(false)});return()=>{active=false}},[view])
 const marketingNames=useMemo(()=>[...new Set(agents.map(row=>row.marketing_name).filter(Boolean))].sort(),[agents])
 const appByAgent=useMemo(()=>new Map(applications.map(row=>[row.userId,row])),[applications])
 const rows=useMemo(()=>agents.filter(row=>{const hay=`${row.name} ${row.store_name||''} ${row.phone||''} ${row.marketing_name||''}`.toLowerCase();const matchesQuery=hay.includes(query.toLowerCase());const matchesMarketing=marketing==='SEMUA'||row.marketing_name===marketing;const app=appByAgent.get(row.id);const matchesFilter=filter==='SEMUA'||filter===row.activity_status||filter==='MODAL_AKTIF'&&Number(app?.capitalOutstanding||0)>0||filter==='MENUNGGU'&&app?.status==='Menunggu keputusan operator';return matchesQuery&&matchesMarketing&&matchesFilter}),[agents,appByAgent,filter,marketing,query])
 const pending=applications.filter(row=>row.status==='Menunggu keputusan operator')
 const activeCapital=applications.filter(row=>row.status==='Disetujui'&&Number(row.capitalOutstanding||row.approvedCapital||0)>0)
 const agentIds=useMemo(()=>new Set(agents.map(row=>String(row.id))),[agents])
 const agentTransactions=useMemo(()=>transactions.filter(row=>{const role=String(row.user_role||row.UserRole||row.role||'').toLowerCase(),userId=String(row.user_id||row.UserID||'');return role==='agent'||(!role&&agentIds.has(userId))}),[transactions,agentIds])
 const transactionCount=days=>{const since=loadedAt-days*86400000;return agentTransactions.filter(row=>new Date(row.created_at||row.CreatedAt||row.date||0).getTime()>=since).length}
 const viewTitle={overview:'Dashboard Operator','pinjaman-retail':'Pinjaman Modal Retail','konter-tidak-transaksi':'Konter Tidak Transaksi',bank:'Bank & Transfer', 'mapping-provider':'Mapping Provider','transaksi-retail':'Transaksi Retail','transaksi-provider':'Transaksi Provider','audit-provider':'Audit Status Provider'}[view]||'Dashboard Operator'
 const workflow={
  'pinjaman-retail':['Periksa pengajuan, identitas, dokumen, dan penanggung jawab','Tetapkan nominal atau tolak dengan alasan yang jelas','Keputusan dan pembayaran tersimpan pada riwayat pinjaman'],
  'konter-tidak-transaksi':['Urutkan konter berdasarkan aktivitas terakhir','Kirim instruksi tindak lanjut ke Marketing penanggung jawab','Hasil kontak atau kunjungan tercatat untuk audit'],
  bank:['Cari produk transfer bank resmi dari katalog H2H','Periksa SKU, bank tujuan, biaya, dan status produk','Mapping bank siap digunakan tanpa membuka PIN provider'],
  'mapping-provider':['Cocokkan layanan KuotaKita dengan SKU Pulsa24Jam','Periksa kategori, provider, tipe harga, dan status','Produk aktif dapat ditelusuri Operator dengan jelas'],
  'transaksi-retail':['Cari transaksi berdasarkan Agent, tujuan, atau referensi','Periksa status transaksi retail dari server KuotaKita','Reference ID tersedia untuk penelusuran kendala'],
  'transaksi-provider':['Pantau order PAY yang benar-benar dikirim ke Pulsa24Jam','Cocokkan produk, tujuan, status, dan pesan provider','Operator melihat log tanpa akses saldo induk atau PIN'],
  'audit-provider':['Tinjau transaksi pending, gagal, dan berhasil','Bandingkan status akhir serta pesan dari provider','Mismatch dapat diteruskan kepada Super Admin'],
 }[view]
 const decide=async(status)=>{if(!selected)return;const approved=Number(amount||formOf(selected).amount||0);if(status==='Disetujui'&&approved<=0)return setMessage('Masukkan nominal modal yang disetujui.');if(status!=='Disetujui'&&!note.trim())return setMessage('Alasan keputusan wajib diisi.');setMessage('Menyimpan keputusan...');try{await request(`/agent-credit/applications/${encodeURIComponent(selected.id)}`,{method:'PUT',body:JSON.stringify({...selected,status,approvedCapital:approved,capitalLimit:approved,capitalStatus:status==='Disetujui'?'Aktif':'Ditolak',partnershipStatus:status==='Disetujui'?'ACTIVE':selected.partnershipStatus,operatorDecision:{status,note:note.trim(),at:new Date().toISOString()}})});setSelected(null);setNote('');setAmount('');setMessage(status==='Disetujui'?'Modal disetujui dan masuk ke Saldo Utama Agent.':'Pengajuan ditolak.');load()}catch(err){setMessage(err.message||'Keputusan belum dapat disimpan.')}}
 const followUp=async(agent,status)=>{try{await updateAgentFollowUp(agent.id,status,`Instruksi Operator: ${status}`);setMessage('Status tindak lanjut berhasil diperbarui.');load()}catch(err){setMessage(err.message||'Status belum dapat diperbarui.')}}
 if(loading)return <section className="operator-capital-state">Memuat ruang kerja Operator...</section>
 return <section className="operator-capital-console">
  {view==='overview'&&<><header className="operator-capital-hero"><div><span>RUANG KERJA OPERATOR</span><h1>{viewTitle}</h1><p>Kontrol Agent, pengajuan modal, aktivitas, risiko, dan koordinasi lapangan dalam alur kerja yang tercatat.</p></div><i><ShieldCheck/></i></header>{workflow&&<div className="operator-workflow-guide"><span><b>Yang diperiksa</b>{workflow[0]}</span><span><b>Tindakan Operator</b>{workflow[1]}</span><span><b>Hasil tercatat</b>{workflow[2]}</span></div>}</>}
  {error&&<p className="operator-capital-alert error">{error}</p>}{message&&<p className="operator-capital-alert">{message}</p>}
  {view==='overview'&&<><div className="operator-capital-metrics"><article><span>Agent Aktif</span><strong>{agents.filter(row=>row.activity_status==='ACTIVE').length}</strong><small>Dari {agents.length} Agent terdaftar</small></article><article><span>Tidak Aktif 2+ Hari</span><strong>{agents.filter(row=>Number(row.inactive_days||0)>=2).length}</strong><small>Perlu pemantauan aktivitas</small></article><article><span>Menunggu Keputusan</span><strong>{pending.length}</strong><small>Pengajuan langsung dari Agent</small></article><article><span>Total Modal Aktif</span><strong>{activeCapital.length}</strong><small>{rupiah(activeCapital.reduce((sum,row)=>sum+Number(row.capitalOutstanding||row.approvedCapital||0),0))}</small></article><article><span>Transaksi Hari Ini</span><strong>{transactionCount(1)}</strong><small>Aktivitas Agent 24 jam terakhir</small></article><article><span>Transaksi 7 Hari</span><strong>{transactionCount(7)}</strong><small>Tren operasional mingguan</small></article><article><span>Transaksi 30 Hari</span><strong>{transactionCount(30)}</strong><small>Aktivitas satu bulan</small></article><article><span>Perlu Follow-up</span><strong>{agents.filter(row=>row.activity_status==='NEED_FOLLOW_UP').length}</strong><small>Harus dikoordinasikan ke Marketing</small></article></div><AgentMonitor rows={rows.slice(0,8)} appByAgent={appByAgent} onDetail={setSelected}/><RecentOperatorActivity transactions={agentTransactions} agents={agents}/></>}
  {view==='verifikasi'&&<VerificationQueue pending={pending} agents={agents} onInspect={item=>{setSelected(item);setAmount(String(formOf(item).amount||''))}}/>}
  {view==='peminjam'&&<><OperatorFilters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} marketing={marketing} setMarketing={setMarketing} marketingNames={marketingNames}/><AgentMonitor rows={rows} appByAgent={appByAgent} onDetail={setSelected}/></>}
  {view==='suspend'&&<section className="operator-capital-block"><BlockTitle icon={AlertTriangle} title="Status dan risiko kemitraan" note="Tinjau Agent yang tidak aktif, catat hasil pemeriksaan lapangan, lalu tetapkan tindak lanjut yang dapat dipertanggungjawabkan."/><div className="operator-capital-list">{agents.filter(row=>row.activity_status!=='ACTIVE'||row.partnership_status==='PARTNERSHIP_ENDED').map(agent=><article key={agent.id}><div><b>{agent.name}</b><small>{agent.store_name||'Toko belum dilengkapi'} · {statusLabel(agent.activity_status)}</small></div><button onClick={()=>followUp(agent,'VISITED')}>Sudah diperiksa</button><button className="danger" onClick={()=>followUp(agent,'WANTS_TO_STOP')}>Ajukan putus mitra</button></article>)}{!agents.some(row=>row.activity_status!=='ACTIVE')&&<p>Tidak ada risiko aktif. Seluruh Agent dalam kondisi normal.</p>}</div></section>}
  {view==='laporan'&&<section className="operator-capital-block"><BlockTitle icon={UserCheck} title="Penugasan tindak lanjut" note="Kirim tugas yang jelas kepada Marketing penanggung jawab dan pantau hasil kontak atau kunjungan Agent."/><div className="operator-capital-list">{agents.filter(row=>['NEED_FOLLOW_UP','NO_TRANSACTION'].includes(row.activity_status)).map(agent=><article key={agent.id}><div><b>{agent.name}</b><small>{agent.marketing_name||'Marketing belum terhubung'} · {statusLabel(agent.activity_status)}</small></div><button onClick={()=>followUp(agent,'CONTACTED')}>Tugaskan kontak</button><button onClick={()=>followUp(agent,'VISITED')}>Tugaskan kunjungan</button></article>)}{!agents.some(row=>['NEED_FOLLOW_UP','NO_TRANSACTION'].includes(row.activity_status))&&<p>Semua Agent sudah tertangani. Belum ada tugas lapangan baru.</p>}</div></section>}
  {view==='kinerja-marketing'&&<MarketingPerformance agents={agents}/>} 
  {view==='pengajuan-modal'&&<VerificationQueue pending={pending} agents={agents} onInspect={item=>{setSelected(item);setAmount(String(formOf(item).amount||''))}}/>}
  {view==='agent'&&<><OperatorFilters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} marketing={marketing} setMarketing={setMarketing} marketingNames={marketingNames}/><AgentMonitor rows={rows} appByAgent={appByAgent} onDetail={setSelected}/></>}
  {view==='modal-limit'&&<CapitalLimitTable agents={agents} appByAgent={appByAgent} onDetail={setSelected}/>}
  {view==='transaksi-agent'&&<AgentTransactions transactions={transactions} agents={agents}/>}
  {view==='monitoring-agent'&&<AgentHealth agents={agents} appByAgent={appByAgent} onFollowUp={followUp}/>}
  {view==='follow-up'&&<FollowUpWorkspace agents={agents} onFollowUp={followUp}/>}
  {view==='penagihan'&&<CollectionWorkspace agents={agents} appByAgent={appByAgent} onFollowUp={followUp}/>}
  {view==='marketing'&&<MarketingPerformance agents={agents}/>}
  {view==='pengaturan'&&<OperatorSettings/>}
  {view==='pinjaman-retail'&&<RetailLoanWorkspace applications={applications} agents={agents} onRefresh={load} onInspect={item=>{setSelected(item);setAmount(String(formOf(item).amount||item.approvedCapital||''))}}/>}
  {view==='konter-tidak-transaksi'&&<AgentHealth agents={agents} appByAgent={appByAgent} onFollowUp={followUp} onRefresh={load}/>}
  {view==='bank'&&<ProviderCatalog products={providerProducts} loading={providerLoading} bankOnly/>}
  {view==='mapping-provider'&&<ProviderCatalog products={providerProducts} loading={providerLoading}/>}
  {view==='transaksi-retail'&&<AgentTransactions transactions={agentTransactions} agents={agents}/>}
  {view==='transaksi-provider'&&<ProviderLedger orders={providerOrders} loading={providerLoading}/>}
  {view==='audit-provider'&&<ProviderLedger orders={providerOrders} loading={providerLoading} auditOnly/>}
  {selected&&<ApplicationDialog item={selected} agent={agents.find(row=>row.id===selected.userId)} amount={amount} setAmount={setAmount} note={note} setNote={setNote} onClose={()=>setSelected(null)} onApprove={()=>decide('Disetujui')} onReject={()=>decide('Ditolak Permanen')}/>} 
 </section>
}

function BlockTitle({icon:Icon,title,note}){return <header className="operator-capital-title"><i><Icon/></i><div><h2>{title}</h2><p>{note}</p></div></header>}
function RetailLoanWorkspace({applications,agents,onInspect,onRefresh}){const[q,setQ]=useState(''),[tab,setTab]=useState('PENGAJUAN'),[status,setStatus]=useState('MENUNGGU');const names=new Map(agents.map(agent=>[agent.id,agent.name]));const rows=applications.filter(item=>{const form=formOf(item),state=String(item.status||'').toUpperCase();return (status==='SEMUA'||state.includes(status))&&`${item.id} ${form.agentName||names.get(item.userId)||''} ${form.email||''}`.toLowerCase().includes(q.toLowerCase())});return <section className="operator-retail-loans"><header className="operator-p24-page-head"><span>RETAIL AGENT CREDIT</span><h2>Pinjaman Modal Retail</h2><p>Verifikasi dokumen dan review pengajuan modal Agent tanpa bunga dan tanpa tempo.</p></header><div className="operator-loan-toolbar"><nav><button className={tab==='PENGAJUAN'?'active':''} onClick={()=>setTab('PENGAJUAN')}>Pengajuan</button><button className={tab==='DOKUMEN'?'active':''} onClick={()=>setTab('DOKUMEN')}>Dokumen</button></nav><select value={status} onChange={event=>setStatus(event.target.value)}><option value="MENUNGGU">Pending</option><option value="DISETUJUI">Disetujui</option><option value="DITOLAK">Ditolak</option><option value="SEMUA">Semua</option></select><label><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Cari ref, Agent, atau email"/></label><button className="operator-p24-refresh" onClick={onRefresh}>Refresh</button></div>{tab==='DOKUMEN'?<DocumentWorkspace rows={rows} names={names}/>:<div className="operator-loan-groups">{rows.map(item=>{const form=formOf(item),name=form.agentName||names.get(item.userId)||'Agent',state=String(item.status||'Menunggu'),paid=Number(item.paidAmount||0),total=Number(item.approvedCapital||form.amount||0);return <article key={item.id}><header><div><b>{name}</b><small>{form.email||form.whatsapp||'Kontak belum dilengkapi'} · {documentCount(item)} dokumen</small></div><strong>{rupiah(total)}</strong></header><div><code>{item.id}</code><span>Dibayar {rupiah(paid)} · Sisa {rupiah(Math.max(0,total-paid))}</span><em className={state.toLowerCase().includes('tolak')?'failed':state.toLowerCase().includes('setuju')?'success':'pending'}>{state}</em><button onClick={()=>onInspect(item)}><Eye/>Periksa</button></div></article>})}{!rows.length&&<p className="operator-p24-empty-row">Tidak ada pengajuan untuk filter ini.</p>}</div>}</section>}
function DocumentWorkspace({rows,names}){return <div className="operator-document-groups">{rows.map(item=>{const form=formOf(item),documents=Object.entries(item.documents||{});return <article key={item.id}><header><div><b>{form.agentName||names.get(item.userId)||'Agent'}</b><small>{form.email||form.whatsapp||item.id} · {documents.length} dokumen</small></div></header>{documents.map(([key,doc])=>{const source=doc?.image||doc?.dataUrl||'',name=doc?.name||key.replaceAll('_',' '),size=source?Math.max(1,Math.round(source.length*0.75/1024)):0;return <div className="operator-document-row" key={key}><span><b>{name}</b><small>{doc?.fileName||'Dokumen pengajuan'} · versi {doc?.version||1}{size?` · ${size} KB`:''}</small></span><em>{doc?.status||'TERUNGGAH'}</em>{source?<a href={source} target="_blank" rel="noreferrer">Buka</a>:<small>Belum tersedia</small>}</div>})}{!documents.length&&<Empty text="Agent ini belum mengunggah dokumen."/>}</article>})}{!rows.length&&<Empty text="Belum ada dokumen pengajuan."/>}</div>}
function ProviderCatalog({products,loading,bankOnly=false}){const[q,setQ]=useState(''),[category,setCategory]=useState('SEMUA');const source=bankOnly?products.filter(item=>String(item.service||item.category||'').toLowerCase().includes('bank')):products;const categories=[...new Set(source.map(item=>item.category||item.group).filter(Boolean))].sort();const rows=source.filter(item=>(category==='SEMUA'||(item.category||item.group)===category)&&`${item.sku||''} ${item.name||''} ${item.operator||''}`.toLowerCase().includes(q.toLowerCase()));return <section className="operator-capital-block"><BlockTitle icon={bankOnly?Landmark:Boxes} title={bankOnly?'Bank & Transfer H2H':'Mapping Produk Provider'} note={bankOnly?'Daftar transfer bank berasal langsung dari katalog provider H2H.':'Cocokkan SKU provider dengan layanan KuotaKita tanpa membuka kredensial H2H.'}/><div className="operator-capital-filters"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari SKU, provider, atau produk"/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="SEMUA">Semua kategori</option>{categories.map(name=><option key={name}>{name}</option>)}</select></div>{loading?<Empty text="Menghubungkan katalog Pulsa24Jam..."/>:<WorkTable columns={['SKU','Provider','Produk','Kategori','Harga','Tipe']}>{rows.slice(0,150).map(item=><article key={item.sku||item.id}><code>{item.sku||'-'}</code><b>{item.operator||'-'}</b><span>{item.name||'-'}</span><span>{item.category||item.group||'-'}</span><strong>{rupiah(item.harga??item.price??0)}</strong><em>{item.tipe_harga||item.status||'FIXED'}</em></article>)}{!rows.length&&<Empty text="Produk provider belum tersedia atau tidak sesuai filter."/>}</WorkTable>}</section>}
function ProviderLedger({orders,loading,auditOnly=false}){const[q,setQ]=useState(''),[status,setStatus]=useState(auditOnly?'FAILED':'SEMUA');const rows=orders.filter(order=>{const state=String(order.Status||order.status||'pending').toUpperCase();return (status==='SEMUA'||state===status)&&`${order.RefID||''} ${order.Product||''} ${order.Destination||''} ${order.Message||''}`.toLowerCase().includes(q.toLowerCase())});return <section className="operator-capital-block"><BlockTitle icon={auditOnly?ShieldCheck:Activity} title={auditOnly?'Audit Status Provider':'Transaksi Provider H2H'} note={auditOnly?'Periksa transaksi gagal atau tertahan sebelum diteruskan kepada Super Admin.':'Log PAY asli dari backend Pulsa24Jam; saldo induk, API key, dan PIN tetap tersembunyi.'}/><div className="operator-capital-filters"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari ref ID, produk, atau tujuan"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="SEMUA">Semua status</option><option value="SUCCESS">Berhasil</option><option value="PENDING">Diproses</option><option value="FAILED">Gagal</option></select></div>{loading?<Empty text="Menghubungkan log Pulsa24Jam..."/>:<WorkTable columns={['Waktu','Ref ID','Produk','Tujuan','Nominal','Status','Keterangan']}>{rows.map(order=>{const state=String(order.Status||order.status||'pending').toLowerCase();return <article key={order.RefID}><span>{dt(order.CreatedAt)}</span><code>{order.RefID}</code><b>{order.Product||'-'}</b><span>{order.Destination||'-'}</span><strong>{rupiah(order.Amount||0)}</strong><em className={state}>{state==='success'?'Berhasil':state==='failed'?'Gagal':'Diproses'}</em><span>{order.Message||order.SN||'-'}</span></article>})}{!rows.length&&<Empty text="Belum ada transaksi provider yang sesuai filter."/>}</WorkTable>}</section>}
function VerificationQueue({pending,agents,onInspect}){const[q,setQ]=useState(''),[readiness,setReadiness]=useState('SEMUA'),[owner,setOwner]=useState('SEMUA');const owners=[...new Set(pending.map(item=>agents.find(row=>row.id===item.userId)?.marketing_name||item.marketingOwnerName).filter(Boolean))].sort();const filtered=pending.filter(item=>{const form=formOf(item),agent=agents.find(row=>row.id===item.userId),name=agent?.marketing_name||item.marketingOwnerName||'',ready=documentCount(item)>=4&&hasSignature(item),hay=`${form.agentName||item.userName||''} ${form.storeName||''} ${form.whatsapp||''} ${item.id||''} ${name}`.toLowerCase();return hay.includes(q.toLowerCase())&&(owner==='SEMUA'||name===owner)&&(readiness==='SEMUA'||readiness==='SIAP'&&ready||readiness==='PERIKSA'&&!ready)});return <section className="operator-verification-workspace">
 <section className="operator-verification-filter"><header><Filter/><span>FILTER PENGAJUAN</span></header><div><label><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Cari Agent, toko, nomor, atau ID"/></label><select value={owner} onChange={event=>setOwner(event.target.value)}><option value="SEMUA">Semua Marketing</option>{owners.map(name=><option key={name}>{name}</option>)}</select><select value={readiness} onChange={event=>setReadiness(event.target.value)}><option value="SEMUA">Semua Kelengkapan</option><option value="SIAP">Siap Diputuskan</option><option value="PERIKSA">Perlu Pemeriksaan</option></select><button type="button" onClick={()=>{setQ('');setOwner('SEMUA');setReadiness('SEMUA')}}>Reset</button></div></section>
 <section className="operator-capital-block operator-verification-block"><header className="operator-verification-title"><div><span>ANTREAN KEPUTUSAN</span><h2>Verifikasi Pengajuan Agent</h2><p>Buka pengajuan untuk memeriksa data dan menetapkan keputusan.</p></div><strong>{filtered.length}<small>Pengajuan</small></strong></header><div className="operator-verification-head compact"><span>ID Pengajuan</span><span>Nama Agent</span><span>Waktu Masuk</span><span>Nominal</span><span>Marketing</span><span>Status</span><span>Dokumen</span><span>Aksi</span></div><div className="operator-verification-list compact">{filtered.map(item=>{const form=formOf(item),agent=agents.find(row=>row.id===item.userId),docs=documentCount(item),signed=hasSignature(item),ready=docs>=4&&signed;return <article key={item.id}><code data-label="ID Pengajuan">{item.id}</code><span className="verification-agent-name" data-label="Nama Agent"><b>{form.agentName||item.userName||agent?.name||'Agent'}</b></span><time data-label="Waktu Masuk">{dt(item.createdAt)}</time><strong data-label="Nominal">{rupiah(form.amount||0)}</strong><span data-label="Marketing">{agent?.marketing_name||item.marketingOwnerName||'Belum terhubung'}</span><em data-label="Status" className="verification-waiting"><i/>MENUNGGU</em><span data-label="Dokumen" className={ready?'verification-doc-count ready':'verification-doc-count'}>{docs}/4 Dokumen{!signed&&<small> · tanda tangan belum ada</small>}</span><button data-label="Aksi" title={`Periksa ${form.agentName||item.id}`} aria-label={`Periksa pengajuan ${item.id}`} onClick={()=>onInspect(item)}><Eye/><span>Periksa</span></button></article>})}{!filtered.length&&<div className="operator-verification-empty"><CheckCircle2/><b>{pending.length?'Data tidak ditemukan':'Antrean keputusan sudah bersih'}</b><span>{pending.length?'Ubah kata pencarian atau filter kelengkapan.':'Pengajuan baru dari Agent akan otomatis muncul di halaman ini.'}</span></div>}</div></section>
 </section>}
function OperatorFilters({query,setQuery,filter,setFilter,marketing,setMarketing,marketingNames}){return <div className="operator-capital-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari Agent, toko, nomor HP, atau Marketing"/></label><select value={marketing} onChange={e=>setMarketing(e.target.value)}><option value="SEMUA">Semua Marketing</option>{marketingNames.map(name=><option key={name}>{name}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="SEMUA">Semua Agent</option><option value="ACTIVE">Aktif</option><option value="NEED_FOLLOW_UP">Perlu follow-up</option><option value="NO_TRANSACTION">Belum pernah transaksi</option><option value="PARTNERSHIP_ENDED">Putus mitra</option><option value="MODAL_AKTIF">Memiliki modal aktif</option><option value="MENUNGGU">Menunggu approval</option></select></div>}
function AgentMonitor({rows,appByAgent,onDetail}){return <section className="operator-capital-block operator-agent-portfolio"><BlockTitle icon={Users} title="Portofolio Agent" note="Pantau penanggung jawab, aktivitas transaksi, saldo, modal berjalan, dan kondisi akun Agent."/><div className="operator-agent-table"><div className="head"><span>Agent</span><span>Marketing PJ</span><span>Aktivitas Terakhir</span><span>Tidak Aktif</span><span>Saldo Utama</span><span>Modal Berjalan</span><span>Kondisi Akun</span><span>Aksi</span></div>{rows.map(agent=>{const app=appByAgent.get(agent.id);return <article key={agent.id}><span className="agent-identity" data-label="Agent"><b>{agent.name}</b><small>{agent.store_name||agent.phone||agent.id}</small></span><span data-label="Marketing PJ">{agent.marketing_name||'Belum ditentukan'}</span><span data-label="Aktivitas Terakhir">{dt(agent.last_transaction_at)}</span><span data-label="Tidak Aktif">{agent.inactive_days??'-'} hari</span><strong data-label="Saldo Utama">{rupiah(agent.balance||0)}</strong><strong data-label="Modal Berjalan">{rupiah(app?.capitalOutstanding||app?.approvedCapital||0)}</strong><em data-label="Kondisi Akun" className={agent.activity_status}>{statusLabel(agent.activity_status)}</em><button data-label="Aksi" onClick={()=>onDetail(app||{userId:agent.id,userName:agent.name,form:{agentName:agent.name,storeName:agent.store_name,whatsapp:agent.phone},status:'Belum mengajukan'})}><Eye/>Detail</button></article>})}{!rows.length&&<p>Belum ada Agent dalam portofolio.</p>}</div></section>}
function MarketingPerformance({agents}){const groups=Object.values(agents.reduce((all,row)=>{const name=row.marketing_name||'Belum terhubung';all[name]||={name,total:0,active:0,follow:0};all[name].total++;if(row.activity_status==='ACTIVE')all[name].active++;if(row.activity_status==='NEED_FOLLOW_UP')all[name].follow++;return all},{}));return <section className="operator-capital-block"><BlockTitle icon={UserCheck} title="Kinerja tim Marketing" note="Nilai jumlah Agent binaan, tingkat aktivasi, dan penyelesaian tindak lanjut tanpa mencampur kewenangan keputusan Operator."/><div className="operator-marketing-performance"><div className="head"><span>Marketing</span><span>Agent Terdaftar</span><span>Agent Aktif</span><span>Perlu Follow-up</span><span>Aktivasi</span></div>{groups.map(row=><article key={row.name}><b data-label="Marketing">{row.name}</b><span data-label="Agent Terdaftar">{row.total}</span><span data-label="Agent Aktif">{row.active}</span><span data-label="Perlu Follow-up">{row.follow}</span><strong data-label="Aktivasi">{row.total?Math.round(row.active/row.total*100):0}%</strong></article>)}</div></section>}
function RecentOperatorActivity({transactions,agents}){const names=new Map(agents.map(agent=>[String(agent.id),agent.name]));const rows=[...transactions].sort((a,b)=>new Date(b.created_at||b.CreatedAt||0)-new Date(a.created_at||a.CreatedAt||0)).slice(0,8);return <section className="operator-capital-block operator-recent-activity"><BlockTitle icon={ClipboardCheck} title="Aktivitas Agent Terbaru" note="Ringkasan terbaru saja. Buka Log Transaksi untuk pencarian, filter status, dan reference ID lengkap."/><Link className="operator-open-ledger" to="/credit-applications?view=transaksi-agent">Buka Log Transaksi</Link><WorkTable columns={['Waktu','Agent','Aktivitas','Tujuan','Nominal','Status']}>{rows.map((row,index)=>{const state=String(row.status||row.Status||'pending').toLowerCase();return <article key={row.id||row.RefID||index}><span>{dt(row.created_at||row.CreatedAt)}</span><b>{names.get(String(row.user_id||row.UserID))||row.user_name||row.UserName||'Agent'}</b><span>{row.product_name||row.Product||row.type||'Transaksi'}</span><span>{row.destination||row.Destination||'-'}</span><strong>{rupiah(row.amount||row.Qty||row.total||0)}</strong><em className={state}>{state==='success'?'Berhasil':state==='failed'?'Gagal':'Diproses'}</em></article>})}{!rows.length&&<Empty text="Belum ada aktivitas transaksi Agent."/>}</WorkTable></section>}
function CapitalLimitTable({agents,appByAgent,onDetail}){const rows=agents.map(agent=>({agent,app:appByAgent.get(agent.id)})).filter(row=>row.app&&['Disetujui','Lunas'].includes(row.app.status));return <section className="operator-capital-block"><BlockTitle icon={ClipboardCheck} title="Modal & Limit Agent" note="Atur plafon berdasarkan performa. Perubahan limit tidak otomatis menambah Saldo Utama Agent."/><WorkTable columns={['Agent / Konter','Modal Aktif','Limit Sekarang','Sisa Kapasitas','TRX 7 Hari','TRX 30 Hari','Aktivitas Terakhir','Aksi']}>{rows.map(({agent,app})=>{const active=Number(app.capitalOutstanding||app.approvedCapital||0),limit=Number(app.capitalLimit||app.approvedCapital||0);return <article key={agent.id}><Identity agent={agent}/><strong>{rupiah(active)}</strong><strong>{rupiah(limit)}</strong><strong>{rupiah(Math.max(0,limit-active))}</strong><span>{agent.transactions_7d||0}</span><span>{agent.transactions_30d||0}</span><span>{dt(agent.last_transaction_at)}</span><button onClick={()=>onDetail(app)}><Eye/>Detail</button></article>})}{!rows.length&&<Empty text="Belum ada Agent dengan modal atau limit aktif."/>}</WorkTable></section>}
function AgentTransactions({transactions,agents}){const[q,setQ]=useState(''),[status,setStatus]=useState('SEMUA');const names=new Map(agents.map(agent=>[String(agent.id),agent.name]));const rows=transactions.filter(row=>{const role=String(row.user_role||row.UserRole||row.role||'').toLowerCase(),agentName=names.get(String(row.user_id||row.UserID))||row.user_name||row.UserName||'Agent';const state=String(row.status||row.Status||'pending').toUpperCase();const hay=`${agentName} ${row.destination||row.Destination||''} ${row.reference_id||row.RefID||row.id||''}`.toLowerCase();return (!role||role==='agent')&&hay.includes(q.toLowerCase())&&(status==='SEMUA'||state===status)});return <><section className="operator-capital-filters operator-transaction-filters"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari Agent, tujuan, atau reference ID"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="SEMUA">Semua Status</option><option value="SUCCESS">Berhasil</option><option value="PENDING">Diproses</option><option value="FAILED">Gagal</option></select></section><section className="operator-capital-block"><BlockTitle icon={ClipboardCheck} title="Log Transaksi Agent" note="Transaksi operasional Agent dipisahkan dari pencairan dan riwayat modal."/><WorkTable columns={['Waktu','Agent','Jenis','Tujuan','Nominal','Status','Reference ID']}>{rows.map((row,index)=>{const state=String(row.status||row.Status||'pending').toLowerCase();return <article key={row.id||row.RefID||index}><span>{dt(row.created_at||row.CreatedAt)}</span><b>{names.get(String(row.user_id||row.UserID))||row.user_name||row.UserName||'Agent'}</b><span>{row.product_name||row.Product||row.type||'-'}</span><span>{row.destination||row.Destination||'-'}</span><strong>{rupiah(row.amount||row.Qty||row.total||0)}</strong><em className={state}>{state==='success'?'Berhasil':state==='failed'?'Gagal':'Diproses'}</em><code>{row.reference_id||row.RefID||row.id||'-'}</code></article>})}{!rows.length&&<Empty text="Belum ada transaksi Agent yang sesuai filter."/>}</WorkTable></section></>}
function AgentHealth({agents,appByAgent,onFollowUp,onRefresh}){const[days,setDays]=useState(3),[custom,setCustom]=useState(''),[q,setQ]=useState('');const threshold=Math.max(1,days),rows=agents.filter(agent=>Number(agent.inactive_days||0)>=threshold&&`${agent.name} ${agent.store_name||''} ${agent.phone||''} ${agent.marketing_name||''}`.toLowerCase().includes(q.toLowerCase()));const applyCustom=()=>{const value=Number(custom);if(value>0)setDays(value)};return <section className="operator-inactive-workspace"><header className="operator-p24-page-head monitor"><i><AlertTriangle/></i><div><span>MONITORING RETAIL</span><h2>Konter Tidak Transaksi</h2></div></header><div className="operator-inactive-toolbar"><nav>{[[3,'3 Hari'],[7,'1 Minggu'],[14,'2 Minggu'],[21,'3 Minggu'],[30,'1 Bulan']].map(([value,label])=><button key={value} className={days===value?'active':''} onClick={()=>setDays(value)}>{label}</button>)}</nav><div className="operator-custom-days"><input inputMode="numeric" value={custom} onChange={event=>setCustom(event.target.value.replace(/\D/g,''))} placeholder="Jumlah hari"/><button onClick={applyCustom}>Pilih</button></div><label className="search"><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Cari konter, email, atau master"/></label><button className="operator-p24-refresh" onClick={onRefresh}>Refresh</button></div><div className="operator-inactive-summary"><b>Tidak transaksi minimal {threshold} hari</b><span>{rows.length} konter</span></div>{rows.length?<WorkTable columns={['Agent / Konter','Marketing PJ','Aktivitas Terakhir','Tidak Aktif','Modal Aktif','Kondisi','Aksi']}>{rows.map(agent=>{const app=appByAgent.get(agent.id);return <article key={agent.id}><Identity agent={agent}/><span>{agent.marketing_name||'Belum ditentukan'}</span><span>{dt(agent.last_transaction_at)}</span><strong>{agent.inactive_days||0} hari</strong><strong>{rupiah(app?.capitalOutstanding||0)}</strong><em className={agent.activity_status}>{statusLabel(agent.activity_status)}</em><button onClick={()=>onFollowUp(agent,'CONTACTED')}>Minta follow-up</button></article>})}</WorkTable>:<p className="operator-p24-empty-row">Tidak ada konter untuk filter ini.</p>}</section>}
function FollowUpWorkspace({agents,onFollowUp}){const rows=agents.filter(agent=>['NEED_FOLLOW_UP','NO_TRANSACTION'].includes(agent.activity_status)||Number(agent.inactive_days||0)>=2);return <section className="operator-capital-block"><BlockTitle icon={UserCheck} title="Tugas Follow-up Marketing" note="Operator mengirim tugas; Marketing memperbarui hasil kontak atau kunjungan tanpa melihat data finansial Agent."/><div className="operator-capital-list">{rows.map(agent=><article key={agent.id}><div><b>{agent.name}</b><small>{agent.store_name||'Konter belum diisi'} · {agent.marketing_name||'Marketing belum ditentukan'} · {agent.inactive_days||0} hari tidak aktif</small></div><button onClick={()=>onFollowUp(agent,'CONTACTED')}>Tugaskan kontak</button><button onClick={()=>onFollowUp(agent,'VISITED')}>Tugaskan kunjungan</button></article>)}{!rows.length&&<p>Belum ada Agent yang membutuhkan follow-up.</p>}</div></section>}
function CollectionWorkspace({agents,appByAgent,onFollowUp}){const rows=agents.filter(agent=>agent.activity_status==='PARTNERSHIP_ENDED'||agent.partnership_status==='PARTNERSHIP_ENDED');return <section className="operator-capital-block"><BlockTitle icon={AlertTriangle} title="Penagihan & Putus Mitra" note="Hanya Agent yang diputus kemitraannya masuk ke sini; Agent tidak aktif tetap ditangani melalui Monitoring."/><WorkTable columns={['Agent / Konter','Marketing PJ','Modal Dikembalikan','Mulai Penagihan','Status','Aksi']}>{rows.map(agent=>{const app=appByAgent.get(agent.id);return <article key={agent.id}><Identity agent={agent}/><span>{agent.marketing_name||'Belum ditentukan'}</span><strong>{rupiah(app?.capitalOutstanding||0)}</strong><span>{dt(app?.collectionStartedAt)}</span><em>Menunggu Penagihan</em><button onClick={()=>onFollowUp(agent,'COLLECTION_PROCESS')}>Mulai proses</button></article>})}{!rows.length&&<Empty text="Tidak ada Agent dalam proses penagihan atau putus mitra."/>}</WorkTable></section>}
function OperatorSettings(){return <section className="operator-capital-block"><BlockTitle icon={ShieldCheck} title="Aturan Operasional" note="Konfigurasi yang memengaruhi alur kerja Operator. Perubahan sensitif tetap membutuhkan kewenangan Super Admin."/><div className="operator-settings-list"><article><div><b>Batas awal follow-up</b><small>Agent masuk monitoring setelah tidak transaksi selama periode ini.</small></div><strong>2 hari</strong></article><article><div><b>Eskalasi risiko</b><small>Agent tanpa transaksi diprioritaskan untuk kunjungan lapangan.</small></div><strong>3 hari</strong></article><article><div><b>Pencairan modal</b><small>Limit dan pencairan merupakan dua tindakan yang berbeda.</small></div><strong>Manual & tercatat</strong></article><article><div><b>Audit keputusan</b><small>Riwayat keputusan tidak dapat dihapus oleh Operator.</small></div><strong>Aktif</strong></article></div></section>}
function Identity({agent}){return <span className="agent-identity"><b>{agent.name}</b><small>{agent.store_name||agent.phone||agent.id}</small></span>}
function Empty({text}){return <p className="operator-work-empty">{text}</p>}
function WorkTable({columns,children}){return <div className="operator-work-table" style={{'--operator-columns':`repeat(${columns.length},minmax(120px,1fr))`}}><div className="head">{columns.map(column=><span key={column}>{column}</span>)}</div>{children}</div>}
function ApplicationDialog({item,agent,amount,setAmount,note,setNote,onClose,onApprove,onReject}){const form=formOf(item),docs=item.documents&&typeof item.documents==='object'?Object.entries(item.documents):[];return <div className="operator-capital-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><article><header><div><span>PEMERIKSAAN OPERATOR</span><h2>{form.agentName||item.userName}</h2><p>{form.storeName||item.id}</p></div><button onClick={onClose}><X/></button></header><dl><div><dt>ID Pengajuan</dt><dd>{item.id||'Belum mengajukan'}</dd></div><div><dt>Marketing</dt><dd>{agent?.marketing_name||item.marketingOwnerName||'-'}</dd></div><div><dt>Nomor HP</dt><dd>{form.whatsapp||agent?.phone||'-'}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Nominal diminta</dt><dd>{rupiah(form.amount||0)}</dd></div><div><dt>Dokumen</dt><dd>{docs.length} file</dd></div></dl>{docs.length>0&&<div className="operator-capital-docs">{docs.map(([key,doc])=><figure key={key}>{doc?.image?<img src={doc.image} alt={doc.name||key}/>:<span>Pratinjau tidak tersedia</span>}<figcaption>{doc?.name||key}</figcaption></figure>)}</div>}{item.id&&<><label>Nominal modal disetujui<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))}/></label><label>Catatan keputusan<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Wajib diisi untuk penolakan"/></label><footer><button className="danger" onClick={onReject}>Tolak</button><button className="approve" onClick={onApprove}><CheckCircle2/>Setujui &amp; cairkan</button></footer></>}</article></div>}
