import {useEffect,useMemo,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {AlertTriangle,CheckCircle2,ClipboardCheck,Eye,Filter,Search,ShieldCheck,UserCheck,Users,X} from 'lucide-react'
import {request} from '../services/http'
import {listManagedAgents,updateAgentFollowUp} from '../services/authService'
import {rupiah} from '../utils/currency'

const dt=value=>value?new Date(value).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'Belum pernah'
const statusLabel=value=>({ACTIVE:'Aktif',NEED_FOLLOW_UP:'Perlu follow-up',NO_TRANSACTION:'Belum transaksi',PARTNERSHIP_ENDED:'Putus mitra'}[value]||value||'Belum transaksi')
const formOf=item=>item?.form||{}
const documentCount=item=>Object.values(item?.documents||{}).filter(doc=>doc?.image||doc?.dataUrl).length
const hasSignature=item=>Boolean(item?.agentConsent?.signature||item?.agentSignature?.image||item?.signature)

export default function OperatorCapitalConsole(){
 const [params]=useSearchParams(),view=params.get('view')||'overview'
 const [agents,setAgents]=useState([]),[applications,setApplications]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('SEMUA'),[marketing,setMarketing]=useState('SEMUA'),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[amount,setAmount]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [agentRows,applicationRows]=await Promise.all([listManagedAgents(),request('/agent-credit/applications')]);setAgents(Array.isArray(agentRows)?agentRows:[]);setApplications(Array.isArray(applicationRows)?applicationRows:[])}catch(err){setError(err.message||'Data Operator belum dapat dimuat.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const marketingNames=useMemo(()=>[...new Set(agents.map(row=>row.marketing_name).filter(Boolean))].sort(),[agents])
 const appByAgent=useMemo(()=>new Map(applications.map(row=>[row.userId,row])),[applications])
 const rows=useMemo(()=>agents.filter(row=>{const hay=`${row.name} ${row.store_name||''} ${row.phone||''} ${row.marketing_name||''}`.toLowerCase();const matchesQuery=hay.includes(query.toLowerCase());const matchesMarketing=marketing==='SEMUA'||row.marketing_name===marketing;const app=appByAgent.get(row.id);const matchesFilter=filter==='SEMUA'||filter===row.activity_status||filter==='MODAL_AKTIF'&&Number(app?.capitalOutstanding||0)>0||filter==='MENUNGGU'&&app?.status==='Menunggu keputusan operator';return matchesQuery&&matchesMarketing&&matchesFilter}),[agents,applications,appByAgent,filter,marketing,query])
 const pending=applications.filter(row=>row.status==='Menunggu keputusan operator')
 const activeCapital=applications.filter(row=>row.status==='Disetujui'&&Number(row.capitalOutstanding||row.approvedCapital||0)>0)
 const decide=async(status)=>{if(!selected)return;const approved=Number(amount||formOf(selected).amount||0);if(status==='Disetujui'&&approved<=0)return setMessage('Masukkan nominal modal yang disetujui.');if(status!=='Disetujui'&&!note.trim())return setMessage('Alasan keputusan wajib diisi.');setMessage('Menyimpan keputusan...');try{await request(`/agent-credit/applications/${encodeURIComponent(selected.id)}`,{method:'PUT',body:JSON.stringify({...selected,status,approvedCapital:approved,capitalLimit:approved,capitalStatus:status==='Disetujui'?'Aktif':'Ditolak',partnershipStatus:status==='Disetujui'?'ACTIVE':selected.partnershipStatus,operatorDecision:{status,note:note.trim(),at:new Date().toISOString()}})});setSelected(null);setNote('');setAmount('');setMessage(status==='Disetujui'?'Modal disetujui dan masuk ke Saldo Utama Agent.':'Pengajuan ditolak.');load()}catch(err){setMessage(err.message||'Keputusan belum dapat disimpan.')}}
 const followUp=async(agent,status)=>{try{await updateAgentFollowUp(agent.id,status,`Instruksi Operator: ${status}`);setMessage('Status tindak lanjut berhasil diperbarui.');load()}catch(err){setMessage(err.message||'Status belum dapat diperbarui.')}}
 if(loading)return <section className="operator-capital-state">Memuat ruang kerja Operator...</section>
 return <section className="operator-capital-console">
  <header className="operator-capital-hero"><div><span>RUANG KERJA OPERATOR</span><h1>{view==='verifikasi'?'Verifikasi pengajuan kemitraan':view==='peminjam'?'Portofolio Agent':view==='suspend'?'Status dan risiko kemitraan':view==='laporan'?'Penugasan lapangan':view==='kinerja-marketing'?'Kinerja tim Marketing':'Pusat kendali kemitraan'}</h1><p>Periksa pengajuan, awasi dukungan usaha berjalan, dan pastikan setiap tindak lanjut Agent tercatat dengan jelas.</p></div><i><ShieldCheck/></i></header>
  {error&&<p className="operator-capital-alert error">{error}</p>}{message&&<p className="operator-capital-alert">{message}</p>}
  {view==='overview'&&<><div className="operator-capital-metrics"><article><span>Seluruh Agent</span><strong>{agents.length}</strong><small>Lintas seluruh Marketing</small></article><article><span>Menunggu Keputusan</span><strong>{pending.length}</strong><small>Pengajuan langsung dari Agent</small></article><article><span>Modal Aktif</span><strong>{activeCapital.length}</strong><small>{rupiah(activeCapital.reduce((sum,row)=>sum+Number(row.capitalOutstanding||row.approvedCapital||0),0))}</small></article><article><span>Perlu Follow-up</span><strong>{agents.filter(row=>row.activity_status==='NEED_FOLLOW_UP').length}</strong><small>Aktivitas Agent perlu diperiksa</small></article></div><AgentMonitor rows={rows.slice(0,8)} appByAgent={appByAgent} onDetail={setSelected}/></>}
  {view==='verifikasi'&&<VerificationQueue pending={pending} agents={agents} onInspect={item=>{setSelected(item);setAmount(String(formOf(item).amount||''))}}/>}
  {view==='peminjam'&&<><OperatorFilters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} marketing={marketing} setMarketing={setMarketing} marketingNames={marketingNames}/><AgentMonitor rows={rows} appByAgent={appByAgent} onDetail={setSelected}/></>}
  {view==='suspend'&&<section className="operator-capital-block"><BlockTitle icon={AlertTriangle} title="Status dan risiko kemitraan" note="Tinjau Agent yang tidak aktif, catat hasil pemeriksaan lapangan, lalu tetapkan tindak lanjut yang dapat dipertanggungjawabkan."/><div className="operator-capital-list">{agents.filter(row=>row.activity_status!=='ACTIVE'||row.partnership_status==='PARTNERSHIP_ENDED').map(agent=><article key={agent.id}><div><b>{agent.name}</b><small>{agent.store_name||'Toko belum dilengkapi'} · {statusLabel(agent.activity_status)}</small></div><button onClick={()=>followUp(agent,'VISITED')}>Sudah diperiksa</button><button className="danger" onClick={()=>followUp(agent,'WANTS_TO_STOP')}>Ajukan putus mitra</button></article>)}{!agents.some(row=>row.activity_status!=='ACTIVE')&&<p>Tidak ada risiko aktif. Seluruh Agent dalam kondisi normal.</p>}</div></section>}
  {view==='laporan'&&<section className="operator-capital-block"><BlockTitle icon={UserCheck} title="Penugasan tindak lanjut" note="Kirim tugas yang jelas kepada Marketing penanggung jawab dan pantau hasil kontak atau kunjungan Agent."/><div className="operator-capital-list">{agents.filter(row=>['NEED_FOLLOW_UP','NO_TRANSACTION'].includes(row.activity_status)).map(agent=><article key={agent.id}><div><b>{agent.name}</b><small>{agent.marketing_name||'Marketing belum terhubung'} · {statusLabel(agent.activity_status)}</small></div><button onClick={()=>followUp(agent,'CONTACTED')}>Tugaskan kontak</button><button onClick={()=>followUp(agent,'VISITED')}>Tugaskan kunjungan</button></article>)}{!agents.some(row=>['NEED_FOLLOW_UP','NO_TRANSACTION'].includes(row.activity_status))&&<p>Semua Agent sudah tertangani. Belum ada tugas lapangan baru.</p>}</div></section>}
  {view==='kinerja-marketing'&&<MarketingPerformance agents={agents}/>} 
  {selected&&<ApplicationDialog item={selected} agent={agents.find(row=>row.id===selected.userId)} amount={amount} setAmount={setAmount} note={note} setNote={setNote} onClose={()=>setSelected(null)} onApprove={()=>decide('Disetujui')} onReject={()=>decide('Ditolak Permanen')}/>} 
 </section>
}

function BlockTitle({icon:Icon,title,note}){return <header className="operator-capital-title"><i><Icon/></i><div><h2>{title}</h2><p>{note}</p></div></header>}
function VerificationQueue({pending,agents,onInspect}){const[q,setQ]=useState(''),[readiness,setReadiness]=useState('SEMUA'),[owner,setOwner]=useState('SEMUA');const owners=[...new Set(pending.map(item=>agents.find(row=>row.id===item.userId)?.marketing_name||item.marketingOwnerName).filter(Boolean))].sort();const filtered=pending.filter(item=>{const form=formOf(item),agent=agents.find(row=>row.id===item.userId),name=agent?.marketing_name||item.marketingOwnerName||'',ready=documentCount(item)>=4&&hasSignature(item),hay=`${form.agentName||item.userName||''} ${form.storeName||''} ${form.whatsapp||''} ${item.id||''} ${name}`.toLowerCase();return hay.includes(q.toLowerCase())&&(owner==='SEMUA'||name===owner)&&(readiness==='SEMUA'||readiness==='SIAP'&&ready||readiness==='PERIKSA'&&!ready)});return <section className="operator-verification-workspace">
 <section className="operator-verification-filter"><header><Filter/><span>FILTER PENGAJUAN</span></header><div><label><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Cari Agent, toko, nomor, atau ID"/></label><select value={owner} onChange={event=>setOwner(event.target.value)}><option value="SEMUA">Semua Marketing</option>{owners.map(name=><option key={name}>{name}</option>)}</select><select value={readiness} onChange={event=>setReadiness(event.target.value)}><option value="SEMUA">Semua Kelengkapan</option><option value="SIAP">Siap Diputuskan</option><option value="PERIKSA">Perlu Pemeriksaan</option></select><button type="button" onClick={()=>{setQ('');setOwner('SEMUA');setReadiness('SEMUA')}}>Reset</button></div></section>
 <section className="operator-capital-block operator-verification-block"><header className="operator-verification-title"><div><span>ANTREAN KEPUTUSAN</span><h2>Verifikasi Pengajuan Agent</h2><p>Buka pengajuan untuk memeriksa data dan menetapkan keputusan.</p></div><strong>{filtered.length}<small>Pengajuan</small></strong></header><div className="operator-verification-head compact"><span>ID Pengajuan</span><span>Nama Agent</span><span>Waktu Masuk</span><span>Nominal</span><span>Marketing</span><span>Status</span><span>Dokumen</span><span>Aksi</span></div><div className="operator-verification-list compact">{filtered.map(item=>{const form=formOf(item),agent=agents.find(row=>row.id===item.userId),docs=documentCount(item),signed=hasSignature(item),ready=docs>=4&&signed;return <article key={item.id}><code data-label="ID Pengajuan">{item.id}</code><span className="verification-agent-name" data-label="Nama Agent"><b>{form.agentName||item.userName||agent?.name||'Agent'}</b><small>{form.storeName||agent?.store_name||'Toko belum diisi'}</small></span><time data-label="Waktu Masuk">{dt(item.createdAt)}</time><strong data-label="Nominal">{rupiah(form.amount||0)}</strong><span data-label="Marketing">{agent?.marketing_name||item.marketingOwnerName||'Belum terhubung'}</span><em data-label="Status" className="verification-waiting"><i/>MENUNGGU</em><span data-label="Dokumen" className={ready?'verification-doc-count ready':'verification-doc-count'}>{docs}/4 Dokumen{!signed&&<small> · tanda tangan belum ada</small>}</span><button data-label="Aksi" title={`Periksa ${form.agentName||item.id}`} aria-label={`Periksa pengajuan ${item.id}`} onClick={()=>onInspect(item)}><Eye/><span>Periksa</span></button></article>})}{!filtered.length&&<div className="operator-verification-empty"><CheckCircle2/><b>{pending.length?'Data tidak ditemukan':'Antrean keputusan sudah bersih'}</b><span>{pending.length?'Ubah kata pencarian atau filter kelengkapan.':'Pengajuan baru dari Agent akan otomatis muncul di halaman ini.'}</span></div>}</div></section>
 </section>}
function OperatorFilters({query,setQuery,filter,setFilter,marketing,setMarketing,marketingNames}){return <div className="operator-capital-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari Agent, toko, nomor HP, atau Marketing"/></label><select value={marketing} onChange={e=>setMarketing(e.target.value)}><option value="SEMUA">Semua Marketing</option>{marketingNames.map(name=><option key={name}>{name}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="SEMUA">Semua Agent</option><option value="ACTIVE">Aktif</option><option value="NEED_FOLLOW_UP">Perlu follow-up</option><option value="NO_TRANSACTION">Belum pernah transaksi</option><option value="PARTNERSHIP_ENDED">Putus mitra</option><option value="MODAL_AKTIF">Memiliki modal aktif</option><option value="MENUNGGU">Menunggu approval</option></select></div>}
function AgentMonitor({rows,appByAgent,onDetail}){return <section className="operator-capital-block"><BlockTitle icon={Users} title="Portofolio Agent" note="Pantau aktivitas, saldo utama, dukungan usaha berjalan, dan status kemitraan dalam satu daftar."/><div className="operator-agent-table"><div className="head"><span>Agent / Konter</span><span>Marketing</span><span>Transaksi Terakhir</span><span>Idle</span><span>Saldo Utama</span><span>Dukungan Aktif</span><span>Status</span><span>Aksi</span></div>{rows.map(agent=>{const app=appByAgent.get(agent.id);return <article key={agent.id}><span className="agent-identity" data-label="Agent / Konter"><b>{agent.name}</b><small>{agent.store_name||agent.phone||agent.id}</small></span><span data-label="Marketing">{agent.marketing_name||'-'}</span><span data-label="Transaksi Terakhir">{dt(agent.last_transaction_at)}</span><span data-label="Tidak Aktif">{agent.inactive_days??'-'} hari</span><strong data-label="Saldo Utama">{rupiah(agent.balance||0)}</strong><strong data-label="Dukungan Aktif">{rupiah(app?.capitalOutstanding||app?.approvedCapital||0)}</strong><em data-label="Status" className={agent.activity_status}>{statusLabel(agent.activity_status)}</em><button data-label="Aksi" onClick={()=>onDetail(app||{userId:agent.id,userName:agent.name,form:{agentName:agent.name,storeName:agent.store_name,whatsapp:agent.phone},status:'Belum mengajukan'})}><Eye/>Detail</button></article>})}{!rows.length&&<p>Data Agent tidak ditemukan.</p>}</div></section>}
function MarketingPerformance({agents}){const groups=Object.values(agents.reduce((all,row)=>{const name=row.marketing_name||'Belum terhubung';all[name]||={name,total:0,active:0,follow:0};all[name].total++;if(row.activity_status==='ACTIVE')all[name].active++;if(row.activity_status==='NEED_FOLLOW_UP')all[name].follow++;return all},{}));return <section className="operator-capital-block"><BlockTitle icon={UserCheck} title="Kinerja tim Marketing" note="Nilai jumlah Agent binaan, tingkat aktivasi, dan penyelesaian tindak lanjut tanpa mencampur kewenangan keputusan Operator."/><div className="operator-marketing-performance"><div className="head"><span>Marketing</span><span>Agent Terdaftar</span><span>Agent Aktif</span><span>Perlu Follow-up</span><span>Aktivasi</span></div>{groups.map(row=><article key={row.name}><b data-label="Marketing">{row.name}</b><span data-label="Agent Terdaftar">{row.total}</span><span data-label="Agent Aktif">{row.active}</span><span data-label="Perlu Follow-up">{row.follow}</span><strong data-label="Aktivasi">{row.total?Math.round(row.active/row.total*100):0}%</strong></article>)}</div></section>}
function ApplicationDialog({item,agent,amount,setAmount,note,setNote,onClose,onApprove,onReject}){const form=formOf(item),docs=item.documents&&typeof item.documents==='object'?Object.entries(item.documents):[];return <div className="operator-capital-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><article><header><div><span>PEMERIKSAAN OPERATOR</span><h2>{form.agentName||item.userName}</h2><p>{form.storeName||item.id}</p></div><button onClick={onClose}><X/></button></header><dl><div><dt>ID Pengajuan</dt><dd>{item.id||'Belum mengajukan'}</dd></div><div><dt>Marketing</dt><dd>{agent?.marketing_name||item.marketingOwnerName||'-'}</dd></div><div><dt>Nomor HP</dt><dd>{form.whatsapp||agent?.phone||'-'}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Nominal diminta</dt><dd>{rupiah(form.amount||0)}</dd></div><div><dt>Dokumen</dt><dd>{docs.length} file</dd></div></dl>{docs.length>0&&<div className="operator-capital-docs">{docs.map(([key,doc])=><figure key={key}>{doc?.image?<img src={doc.image} alt={doc.name||key}/>:<span>Pratinjau tidak tersedia</span>}<figcaption>{doc?.name||key}</figcaption></figure>)}</div>}{item.id&&<><label>Nominal modal disetujui<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))}/></label><label>Catatan keputusan<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Wajib diisi untuk penolakan"/></label><footer><button className="danger" onClick={onReject}>Tolak</button><button className="approve" onClick={onApprove}><CheckCircle2/>Setujui &amp; cairkan</button></footer></>}</article></div>}
