import {useEffect,useState} from 'react'
import {Fingerprint,KeyRound,ShieldCheck,Smartphone,Trash2} from 'lucide-react'
import SubPageHeader from '../components/mobile/SubPageHeader'
import MobileNav from '../components/mobile/MobileNav'
import {useAuth} from '../context/AuthContext'
import {biometricAvailable,disableBiometric,enableBiometric,getSecurity,removePin,setPin} from '../services/securityService'

export default function SecurityPage(){
 const{user}=useAuth(),[settings,setSettings]=useState(()=>getSecurity(user.id)),[pin,setPinValue]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>setSettings(getSecurity(user.id)),[user.id])
 const createPin=async event=>{event.preventDefault();setMessage('');if(pin.length!==6)return setMessage('PIN harus terdiri dari 6 angka.');if(pin!==confirm)return setMessage('Konfirmasi PIN belum sama.');setBusy(true);await setPin(user.id,pin);setSettings(getSecurity(user.id));setPinValue('');setConfirm('');setMessage('PIN pembayaran berhasil diaktifkan.');setBusy(false)}
 const fingerprint=async()=>{setBusy(true);setMessage('');try{await enableBiometric(user.id,user.email||user.username);setSettings(getSecurity(user.id));setMessage('Sidik jari berhasil diaktifkan untuk pembayaran.')}catch(error){setMessage(error.name==='NotAllowedError'?'Pendaftaran sidik jari dibatalkan.':error.message)}finally{setBusy(false)}}
 return <main className="mobile-app account-feature-page"><SubPageHeader title="Keamanan Akun" description="PIN dan keamanan perangkat" back/><section className="security-hero"><ShieldCheck/><div><strong>Perlindungan transaksi</strong><p>Aktifkan sesuai kebutuhanmu. Jika tidak diaktifkan, pembayaran tetap berjalan biasa.</p></div></section><section className="account-feature-card"><header><i><KeyRound/></i><div><h2>PIN Pembayaran</h2><p>{settings.pinHash?'Aktif · Diminta sebelum pembayaran':'Belum aktif · Opsional'}</p></div><span className={settings.pinHash?'active':''}>{settings.pinHash?'Aktif':'Nonaktif'}</span></header>{settings.pinHash?<button className="danger-line" onClick={()=>{removePin(user.id);setSettings(getSecurity(user.id));setMessage('PIN pembayaran dinonaktifkan.')}}><Trash2/>Hapus PIN pembayaran</button>:<form className="security-pin-form" onSubmit={createPin}><label>Buat PIN 6 digit<input value={pin} onChange={event=>setPinValue(event.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" type="password" placeholder="••••••"/></label><label>Ulangi PIN<input value={confirm} onChange={event=>setConfirm(event.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" type="password" placeholder="••••••"/></label><button disabled={busy}>Aktifkan PIN</button></form>}</section><section className="account-feature-card"><header><i><Fingerprint/></i><div><h2>Sidik Jari</h2><p>{settings.biometricEnabled?'Terhubung ke perangkat ini':biometricAvailable()?'Siap diaktifkan':'Tidak didukung perangkat'}</p></div><span className={settings.biometricEnabled?'active':''}>{settings.biometricEnabled?'Aktif':'Nonaktif'}</span></header>{settings.biometricEnabled?<button className="danger-line" onClick={()=>{disableBiometric(user.id);setSettings(getSecurity(user.id));setMessage('Sidik jari dinonaktifkan.')}}><Trash2/>Hapus sidik jari</button>:<button className="feature-primary" disabled={busy||!biometricAvailable()} onClick={fingerprint}><Fingerprint/>Daftarkan Sidik Jari</button>}</section><section className="security-device"><Smartphone/><div><strong>Perangkat saat ini</strong><small>Pengaturan hanya berlaku untuk akun dan perangkat ini.</small></div></section>{message&&<div className="feature-message">{message}</div>}<MobileNav/></main>
}
