import {useEffect,useRef,useState} from 'react';import {ChevronLeft,ChevronRight,Gift,WalletCards,Zap,Gamepad2,Wifi,Timer} from 'lucide-react';
const promos=[
  {tag:'PENGGUNA BARU',title:'Cashback hingga 10%',text:'Transaksi pulsa atau paket data pertamamu.',action:'Ambil Promo',icon:Gift,tone:'midnight'},
  {tag:'ISI SALDO',title:'Bonus FastPoint 2×',text:'Top-up saldo minimal Rp100.000 hari ini.',action:'Isi Saldo',icon:WalletCards,tone:'violet'},
  {tag:'PAKET DATA',title:'Hemat sampai Rp15.000',text:'Paket internet semua operator tanpa kode promo.',action:'Beli Paket',icon:Wifi,tone:'ocean'},
  {tag:'VOUCHER GAME',title:'Main lebih untung',text:'Cashback 5% Mobile Legends dan Free Fire.',action:'Top Up Game',icon:Gamepad2,tone:'sunset'},
  {tag:'FLASH SALE',title:'Pulsa mulai Rp5.000',text:'Harga spesial setiap pukul 12.00–14.00 WIB.',action:'Lihat Promo',icon:Zap,tone:'emerald'},
]
export default function PromoSlider(){const[index,setIndex]=useState(0),touch=useRef(null);useEffect(()=>{const timer=setInterval(()=>setIndex(value=>(value+1)%promos.length),4500);return()=>clearInterval(timer)},[]);const move=step=>setIndex(value=>(value+step+promos.length)%promos.length);const promo=promos[index],Icon=promo.icon;return <section className="promo-section premium-promos"><div className="mobile-section-title"><div><h2>Promo Pilihan</h2><small>Penawaran terbaik untukmu</small></div><span>{index+1}/{promos.length}</span></div><div className="promo-carousel" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>40)move(delta<0?1:-1)}}><article className={`promo-slide ${promo.tone}`} key={promo.title}><div className="promo-glow"/><div className="promo-content"><span><Timer/> {promo.tag}</span><h2>{promo.title}</h2><p>{promo.text}</p><button>{promo.action}<ChevronRight/></button></div><div className="promo-art"><i><Icon/></i><b>FastPay</b></div></article><button className="carousel-arrow prev" onClick={()=>move(-1)} aria-label="Promo sebelumnya"><ChevronLeft/></button><button className="carousel-arrow next" onClick={()=>move(1)} aria-label="Promo berikutnya"><ChevronRight/></button></div><div className="promo-dots">{promos.map((item,i)=><button className={i===index?'active':''} onClick={()=>setIndex(i)} key={item.title} aria-label={`Promo ${i+1}`}/>)}</div><p className="promo-note"><Zap/>Promo berganti otomatis setiap beberapa detik.</p></section>}
